// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddEditTransportRule
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddEditTransportRulePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>actionType parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ActionType { get; set; }
#nullable restore
#else
        public List<string> ActionType { get; set; }
#endif
        /// <summary>ActivationDate parameter</summary>
        public DateTimeOffset? ActivationDate { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AnyOfCcHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfCcHeader { get; set; }
#nullable restore
#else
        public string AnyOfCcHeader { get; set; }
#endif
        /// <summary>AnyOfCcHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfCcHeaderMemberOf { get; set; }
#nullable restore
#else
        public string AnyOfCcHeaderMemberOf { get; set; }
#endif
        /// <summary>AnyOfRecipientAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfRecipientAddressContainsWords { get; set; }
#nullable restore
#else
        public string AnyOfRecipientAddressContainsWords { get; set; }
#endif
        /// <summary>AnyOfRecipientAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfRecipientAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string AnyOfRecipientAddressMatchesPatterns { get; set; }
#endif
        /// <summary>AnyOfToCcHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfToCcHeader { get; set; }
#nullable restore
#else
        public string AnyOfToCcHeader { get; set; }
#endif
        /// <summary>AnyOfToCcHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfToCcHeaderMemberOf { get; set; }
#nullable restore
#else
        public string AnyOfToCcHeaderMemberOf { get; set; }
#endif
        /// <summary>AnyOfToHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfToHeader { get; set; }
#nullable restore
#else
        public string AnyOfToHeader { get; set; }
#endif
        /// <summary>AnyOfToHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnyOfToHeaderMemberOf { get; set; }
#nullable restore
#else
        public string AnyOfToHeaderMemberOf { get; set; }
#endif
        /// <summary>ApplyClassification parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplyClassification { get; set; }
#nullable restore
#else
        public string ApplyClassification { get; set; }
#endif
        /// <summary>ApplyHtmlDisclaimerFallbackAction parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ApplyHtmlDisclaimerFallbackAction { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ApplyHtmlDisclaimerFallbackAction { get; set; }
#endif
        /// <summary>ApplyHtmlDisclaimerLocation parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ApplyHtmlDisclaimerLocation { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ApplyHtmlDisclaimerLocation { get; set; }
#endif
        /// <summary>ApplyHtmlDisclaimerText parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplyHtmlDisclaimerText { get; set; }
#nullable restore
#else
        public string ApplyHtmlDisclaimerText { get; set; }
#endif
        /// <summary>ApplyOME parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplyOME { get; set; }
#nullable restore
#else
        public string ApplyOME { get; set; }
#endif
        /// <summary>applyToAllMessages parameter</summary>
        public bool? ApplyToAllMessages { get; set; }
        /// <summary>AttachmentContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentContainsWords { get; set; }
#nullable restore
#else
        public string AttachmentContainsWords { get; set; }
#endif
        /// <summary>AttachmentExtensionMatchesWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentExtensionMatchesWords { get; set; }
#nullable restore
#else
        public string AttachmentExtensionMatchesWords { get; set; }
#endif
        /// <summary>The AttachmentHasExecutableContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentHasExecutableContent { get; set; }
#nullable restore
#else
        public string AttachmentHasExecutableContent { get; set; }
#endif
        /// <summary>The AttachmentIsPasswordProtected property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentIsPasswordProtected { get; set; }
#nullable restore
#else
        public string AttachmentIsPasswordProtected { get; set; }
#endif
        /// <summary>The AttachmentIsUnsupported property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentIsUnsupported { get; set; }
#nullable restore
#else
        public string AttachmentIsUnsupported { get; set; }
#endif
        /// <summary>AttachmentMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentMatchesPatterns { get; set; }
#nullable restore
#else
        public string AttachmentMatchesPatterns { get; set; }
#endif
        /// <summary>The AttachmentNameMatchesPatterns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentNameMatchesPatterns { get; set; }
#nullable restore
#else
        public string AttachmentNameMatchesPatterns { get; set; }
#endif
        /// <summary>The AttachmentProcessingLimitExceeded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentProcessingLimitExceeded { get; set; }
#nullable restore
#else
        public string AttachmentProcessingLimitExceeded { get; set; }
#endif
        /// <summary>The AttachmentPropertyContainsWords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentPropertyContainsWords { get; set; }
#nullable restore
#else
        public string AttachmentPropertyContainsWords { get; set; }
#endif
        /// <summary>AttachmentSizeOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachmentSizeOver { get; set; }
#nullable restore
#else
        public string AttachmentSizeOver { get; set; }
#endif
        /// <summary>BlindCopyTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlindCopyTo { get; set; }
#nullable restore
#else
        public string BlindCopyTo { get; set; }
#endif
        /// <summary>Comments parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>conditionType parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConditionType { get; set; }
#nullable restore
#else
        public List<string> ConditionType { get; set; }
#endif
        /// <summary>CopyTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CopyTo { get; set; }
#nullable restore
#else
        public string CopyTo { get; set; }
#endif
        /// <summary>Body parameter from PS1: Count</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Count { get; set; }
#nullable restore
#else
        public string Count { get; set; }
#endif
        /// <summary>DeleteMessage parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeleteMessage { get; set; }
#nullable restore
#else
        public string DeleteMessage { get; set; }
#endif
        /// <summary>Enabled parameter</summary>
        public bool? Enabled { get; set; }
        /// <summary>ExceptIfAnyOfCcHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfCcHeader { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfCcHeader { get; set; }
#endif
        /// <summary>ExceptIfAnyOfCcHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfCcHeaderMemberOf { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfCcHeaderMemberOf { get; set; }
#endif
        /// <summary>ExceptIfAnyOfRecipientAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfRecipientAddressContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfRecipientAddressContainsWords { get; set; }
#endif
        /// <summary>ExceptIfAnyOfRecipientAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfRecipientAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfRecipientAddressMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfAnyOfToCcHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfToCcHeader { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfToCcHeader { get; set; }
#endif
        /// <summary>ExceptIfAnyOfToCcHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfToCcHeaderMemberOf { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfToCcHeaderMemberOf { get; set; }
#endif
        /// <summary>ExceptIfAnyOfToHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfToHeader { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfToHeader { get; set; }
#endif
        /// <summary>ExceptIfAnyOfToHeaderMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAnyOfToHeaderMemberOf { get; set; }
#nullable restore
#else
        public string ExceptIfAnyOfToHeaderMemberOf { get; set; }
#endif
        /// <summary>ExceptIfAttachmentContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentContainsWords { get; set; }
#endif
        /// <summary>ExceptIfAttachmentExtensionMatchesWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentExtensionMatchesWords { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentExtensionMatchesWords { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentHasExecutableContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentHasExecutableContent { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentHasExecutableContent { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentIsPasswordProtected property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentIsPasswordProtected { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentIsPasswordProtected { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentIsUnsupported property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentIsUnsupported { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentIsUnsupported { get; set; }
#endif
        /// <summary>ExceptIfAttachmentMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentMatchesPatterns { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentNameMatchesPatterns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentNameMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentNameMatchesPatterns { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentProcessingLimitExceeded property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentProcessingLimitExceeded { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentProcessingLimitExceeded { get; set; }
#endif
        /// <summary>The ExceptIfAttachmentPropertyContainsWords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentPropertyContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentPropertyContainsWords { get; set; }
#endif
        /// <summary>ExceptIfAttachmentSizeOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfAttachmentSizeOver { get; set; }
#nullable restore
#else
        public string ExceptIfAttachmentSizeOver { get; set; }
#endif
        /// <summary>ExceptIfFrom parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfFrom { get; set; }
#nullable restore
#else
        public string ExceptIfFrom { get; set; }
#endif
        /// <summary>ExceptIfFromAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfFromAddressContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfFromAddressContainsWords { get; set; }
#endif
        /// <summary>ExceptIfFromAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfFromAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfFromAddressMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfFromMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfFromMemberOf { get; set; }
#nullable restore
#else
        public string ExceptIfFromMemberOf { get; set; }
#endif
        /// <summary>ExceptIfFromScope parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfFromScope { get; set; }
#nullable restore
#else
        public string ExceptIfFromScope { get; set; }
#endif
        /// <summary>ExceptIfHeaderContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfHeaderContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfHeaderContainsWords { get; set; }
#endif
        /// <summary>ExceptIfHeaderContainsWordsMessageHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfHeaderContainsWordsMessageHeader { get; set; }
#nullable restore
#else
        public string ExceptIfHeaderContainsWordsMessageHeader { get; set; }
#endif
        /// <summary>ExceptIfHeaderMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfHeaderMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfHeaderMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfHeaderMatchesPatternsMessageHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfHeaderMatchesPatternsMessageHeader { get; set; }
#nullable restore
#else
        public string ExceptIfHeaderMatchesPatternsMessageHeader { get; set; }
#endif
        /// <summary>ExceptIfMessageSizeOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfMessageSizeOver { get; set; }
#nullable restore
#else
        public string ExceptIfMessageSizeOver { get; set; }
#endif
        /// <summary>ExceptIfMessageTypeMatches parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfMessageTypeMatches { get; set; }
#nullable restore
#else
        public string ExceptIfMessageTypeMatches { get; set; }
#endif
        /// <summary>ExceptIfRecipientAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfRecipientAddressContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfRecipientAddressContainsWords { get; set; }
#endif
        /// <summary>ExceptIfRecipientAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfRecipientAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfRecipientAddressMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfRecipientDomainIs parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfRecipientDomainIs { get; set; }
#nullable restore
#else
        public string ExceptIfRecipientDomainIs { get; set; }
#endif
        /// <summary>ExceptIfSCLOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSCLOver { get; set; }
#nullable restore
#else
        public string ExceptIfSCLOver { get; set; }
#endif
        /// <summary>ExceptIfSenderDomainIs parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSenderDomainIs { get; set; }
#nullable restore
#else
        public string ExceptIfSenderDomainIs { get; set; }
#endif
        /// <summary>ExceptIfSenderIpRanges parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSenderIpRanges { get; set; }
#nullable restore
#else
        public string ExceptIfSenderIpRanges { get; set; }
#endif
        /// <summary>ExceptIfSentTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSentTo { get; set; }
#nullable restore
#else
        public string ExceptIfSentTo { get; set; }
#endif
        /// <summary>ExceptIfSentToMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSentToMemberOf { get; set; }
#nullable restore
#else
        public string ExceptIfSentToMemberOf { get; set; }
#endif
        /// <summary>ExceptIfSentToScope parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSentToScope { get; set; }
#nullable restore
#else
        public string ExceptIfSentToScope { get; set; }
#endif
        /// <summary>ExceptIfSubjectContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSubjectContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfSubjectContainsWords { get; set; }
#endif
        /// <summary>ExceptIfSubjectMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSubjectMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfSubjectMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfSubjectOrBodyContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSubjectOrBodyContainsWords { get; set; }
#nullable restore
#else
        public string ExceptIfSubjectOrBodyContainsWords { get; set; }
#endif
        /// <summary>ExceptIfSubjectOrBodyMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfSubjectOrBodyMatchesPatterns { get; set; }
#nullable restore
#else
        public string ExceptIfSubjectOrBodyMatchesPatterns { get; set; }
#endif
        /// <summary>ExceptIfWithImportance parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExceptIfWithImportance { get; set; }
#nullable restore
#else
        public string ExceptIfWithImportance { get; set; }
#endif
        /// <summary>exceptionType parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExceptionType { get; set; }
#nullable restore
#else
        public List<string> ExceptionType { get; set; }
#endif
        /// <summary>ExpiryDate parameter</summary>
        public DateTimeOffset? ExpiryDate { get; set; }
        /// <summary>From parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>FromAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromAddressContainsWords { get; set; }
#nullable restore
#else
        public string FromAddressContainsWords { get; set; }
#endif
        /// <summary>FromAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string FromAddressMatchesPatterns { get; set; }
#endif
        /// <summary>FromMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromMemberOf { get; set; }
#nullable restore
#else
        public string FromMemberOf { get; set; }
#endif
        /// <summary>FromScope parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromScope { get; set; }
#nullable restore
#else
        public string FromScope { get; set; }
#endif
        /// <summary>GenerateIncidentReport parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GenerateIncidentReport { get; set; }
#nullable restore
#else
        public string GenerateIncidentReport { get; set; }
#endif
        /// <summary>GenerateNotification parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GenerateNotification { get; set; }
#nullable restore
#else
        public string GenerateNotification { get; set; }
#endif
        /// <summary>HeaderContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderContainsWords { get; set; }
#nullable restore
#else
        public string HeaderContainsWords { get; set; }
#endif
        /// <summary>HeaderContainsWordsMessageHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderContainsWordsMessageHeader { get; set; }
#nullable restore
#else
        public string HeaderContainsWordsMessageHeader { get; set; }
#endif
        /// <summary>HeaderMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderMatchesPatterns { get; set; }
#nullable restore
#else
        public string HeaderMatchesPatterns { get; set; }
#endif
        /// <summary>HeaderMatchesPatternsMessageHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderMatchesPatternsMessageHeader { get; set; }
#nullable restore
#else
        public string HeaderMatchesPatternsMessageHeader { get; set; }
#endif
        /// <summary>The IncidentReportContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? IncidentReportContent { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> IncidentReportContent { get; set; }
#endif
        /// <summary>MessageSizeOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageSizeOver { get; set; }
#nullable restore
#else
        public string MessageSizeOver { get; set; }
#endif
        /// <summary>MessageTypeMatches parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageTypeMatches { get; set; }
#nullable restore
#else
        public string MessageTypeMatches { get; set; }
#endif
        /// <summary>Mode parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Mode { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Mode { get; set; }
#endif
        /// <summary>ModerateMessageByManager parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModerateMessageByManager { get; set; }
#nullable restore
#else
        public string ModerateMessageByManager { get; set; }
#endif
        /// <summary>ModerateMessageByUser parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModerateMessageByUser { get; set; }
#nullable restore
#else
        public string ModerateMessageByUser { get; set; }
#endif
        /// <summary>Name parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>PrependSubject parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrependSubject { get; set; }
#nullable restore
#else
        public string PrependSubject { get; set; }
#endif
        /// <summary>Priority parameter</summary>
        public double? Priority { get; set; }
        /// <summary>Quarantine parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Quarantine { get; set; }
#nullable restore
#else
        public string Quarantine { get; set; }
#endif
        /// <summary>RecipientAddressContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientAddressContainsWords { get; set; }
#nullable restore
#else
        public string RecipientAddressContainsWords { get; set; }
#endif
        /// <summary>RecipientAddressMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientAddressMatchesPatterns { get; set; }
#nullable restore
#else
        public string RecipientAddressMatchesPatterns { get; set; }
#endif
        /// <summary>RecipientDomainIs parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientDomainIs { get; set; }
#nullable restore
#else
        public string RecipientDomainIs { get; set; }
#endif
        /// <summary>RedirectMessageTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectMessageTo { get; set; }
#nullable restore
#else
        public string RedirectMessageTo { get; set; }
#endif
        /// <summary>RejectMessageEnhancedStatusCode parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectMessageEnhancedStatusCode { get; set; }
#nullable restore
#else
        public string RejectMessageEnhancedStatusCode { get; set; }
#endif
        /// <summary>RejectMessageReasonText parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectMessageReasonText { get; set; }
#nullable restore
#else
        public string RejectMessageReasonText { get; set; }
#endif
        /// <summary>RemoveHeader parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveHeader { get; set; }
#nullable restore
#else
        public string RemoveHeader { get; set; }
#endif
        /// <summary>RouteMessageOutboundConnector parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RouteMessageOutboundConnector { get; set; }
#nullable restore
#else
        public string RouteMessageOutboundConnector { get; set; }
#endif
        /// <summary>ruleId parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleId { get; set; }
#nullable restore
#else
        public string RuleId { get; set; }
#endif
        /// <summary>SCLOver parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SCLOver { get; set; }
#nullable restore
#else
        public string SCLOver { get; set; }
#endif
        /// <summary>SenderAddressLocation parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SenderAddressLocation { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SenderAddressLocation { get; set; }
#endif
        /// <summary>SenderDomainIs parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderDomainIs { get; set; }
#nullable restore
#else
        public string SenderDomainIs { get; set; }
#endif
        /// <summary>SenderIpRanges parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderIpRanges { get; set; }
#nullable restore
#else
        public string SenderIpRanges { get; set; }
#endif
        /// <summary>SentTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentTo { get; set; }
#nullable restore
#else
        public string SentTo { get; set; }
#endif
        /// <summary>SentToMemberOf parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentToMemberOf { get; set; }
#nullable restore
#else
        public string SentToMemberOf { get; set; }
#endif
        /// <summary>SentToScope parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentToScope { get; set; }
#nullable restore
#else
        public string SentToScope { get; set; }
#endif
        /// <summary>SetAuditSeverity parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SetAuditSeverity { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SetAuditSeverity { get; set; }
#endif
        /// <summary>SetHeaderName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SetHeaderName { get; set; }
#nullable restore
#else
        public string SetHeaderName { get; set; }
#endif
        /// <summary>SetHeaderValue parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SetHeaderValue { get; set; }
#nullable restore
#else
        public string SetHeaderValue { get; set; }
#endif
        /// <summary>SetSCL parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SetSCL { get; set; }
#nullable restore
#else
        public string SetSCL { get; set; }
#endif
        /// <summary>State parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>StopRuleProcessing parameter</summary>
        public bool? StopRuleProcessing { get; set; }
        /// <summary>SubjectContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectContainsWords { get; set; }
#nullable restore
#else
        public string SubjectContainsWords { get; set; }
#endif
        /// <summary>SubjectMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectMatchesPatterns { get; set; }
#nullable restore
#else
        public string SubjectMatchesPatterns { get; set; }
#endif
        /// <summary>SubjectOrBodyContainsWords parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectOrBodyContainsWords { get; set; }
#nullable restore
#else
        public string SubjectOrBodyContainsWords { get; set; }
#endif
        /// <summary>SubjectOrBodyMatchesPatterns parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectOrBodyMatchesPatterns { get; set; }
#nullable restore
#else
        public string SubjectOrBodyMatchesPatterns { get; set; }
#endif
        /// <summary>tenantFilter parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>Body parameter from PS1: value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>WithImportance parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WithImportance { get; set; }
#nullable restore
#else
        public string WithImportance { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddEditTransportRule.AddEditTransportRulePostRequestBody"/> and sets the default values.
        /// </summary>
        public AddEditTransportRulePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddEditTransportRule.AddEditTransportRulePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddEditTransportRule.AddEditTransportRulePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddEditTransportRule.AddEditTransportRulePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionType", n => { ActionType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ActivationDate", n => { ActivationDate = n.GetDateTimeOffsetValue(); } },
                { "AnyOfCcHeader", n => { AnyOfCcHeader = n.GetStringValue(); } },
                { "AnyOfCcHeaderMemberOf", n => { AnyOfCcHeaderMemberOf = n.GetStringValue(); } },
                { "AnyOfRecipientAddressContainsWords", n => { AnyOfRecipientAddressContainsWords = n.GetStringValue(); } },
                { "AnyOfRecipientAddressMatchesPatterns", n => { AnyOfRecipientAddressMatchesPatterns = n.GetStringValue(); } },
                { "AnyOfToCcHeader", n => { AnyOfToCcHeader = n.GetStringValue(); } },
                { "AnyOfToCcHeaderMemberOf", n => { AnyOfToCcHeaderMemberOf = n.GetStringValue(); } },
                { "AnyOfToHeader", n => { AnyOfToHeader = n.GetStringValue(); } },
                { "AnyOfToHeaderMemberOf", n => { AnyOfToHeaderMemberOf = n.GetStringValue(); } },
                { "ApplyClassification", n => { ApplyClassification = n.GetStringValue(); } },
                { "ApplyHtmlDisclaimerFallbackAction", n => { ApplyHtmlDisclaimerFallbackAction = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "ApplyHtmlDisclaimerLocation", n => { ApplyHtmlDisclaimerLocation = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "ApplyHtmlDisclaimerText", n => { ApplyHtmlDisclaimerText = n.GetStringValue(); } },
                { "ApplyOME", n => { ApplyOME = n.GetStringValue(); } },
                { "applyToAllMessages", n => { ApplyToAllMessages = n.GetBoolValue(); } },
                { "AttachmentContainsWords", n => { AttachmentContainsWords = n.GetStringValue(); } },
                { "AttachmentExtensionMatchesWords", n => { AttachmentExtensionMatchesWords = n.GetStringValue(); } },
                { "AttachmentHasExecutableContent", n => { AttachmentHasExecutableContent = n.GetStringValue(); } },
                { "AttachmentIsPasswordProtected", n => { AttachmentIsPasswordProtected = n.GetStringValue(); } },
                { "AttachmentIsUnsupported", n => { AttachmentIsUnsupported = n.GetStringValue(); } },
                { "AttachmentMatchesPatterns", n => { AttachmentMatchesPatterns = n.GetStringValue(); } },
                { "AttachmentNameMatchesPatterns", n => { AttachmentNameMatchesPatterns = n.GetStringValue(); } },
                { "AttachmentProcessingLimitExceeded", n => { AttachmentProcessingLimitExceeded = n.GetStringValue(); } },
                { "AttachmentPropertyContainsWords", n => { AttachmentPropertyContainsWords = n.GetStringValue(); } },
                { "AttachmentSizeOver", n => { AttachmentSizeOver = n.GetStringValue(); } },
                { "BlindCopyTo", n => { BlindCopyTo = n.GetStringValue(); } },
                { "Comments", n => { Comments = n.GetStringValue(); } },
                { "conditionType", n => { ConditionType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "CopyTo", n => { CopyTo = n.GetStringValue(); } },
                { "Count", n => { Count = n.GetStringValue(); } },
                { "DeleteMessage", n => { DeleteMessage = n.GetStringValue(); } },
                { "Enabled", n => { Enabled = n.GetBoolValue(); } },
                { "ExceptIfAnyOfCcHeader", n => { ExceptIfAnyOfCcHeader = n.GetStringValue(); } },
                { "ExceptIfAnyOfCcHeaderMemberOf", n => { ExceptIfAnyOfCcHeaderMemberOf = n.GetStringValue(); } },
                { "ExceptIfAnyOfRecipientAddressContainsWords", n => { ExceptIfAnyOfRecipientAddressContainsWords = n.GetStringValue(); } },
                { "ExceptIfAnyOfRecipientAddressMatchesPatterns", n => { ExceptIfAnyOfRecipientAddressMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfAnyOfToCcHeader", n => { ExceptIfAnyOfToCcHeader = n.GetStringValue(); } },
                { "ExceptIfAnyOfToCcHeaderMemberOf", n => { ExceptIfAnyOfToCcHeaderMemberOf = n.GetStringValue(); } },
                { "ExceptIfAnyOfToHeader", n => { ExceptIfAnyOfToHeader = n.GetStringValue(); } },
                { "ExceptIfAnyOfToHeaderMemberOf", n => { ExceptIfAnyOfToHeaderMemberOf = n.GetStringValue(); } },
                { "ExceptIfAttachmentContainsWords", n => { ExceptIfAttachmentContainsWords = n.GetStringValue(); } },
                { "ExceptIfAttachmentExtensionMatchesWords", n => { ExceptIfAttachmentExtensionMatchesWords = n.GetStringValue(); } },
                { "ExceptIfAttachmentHasExecutableContent", n => { ExceptIfAttachmentHasExecutableContent = n.GetStringValue(); } },
                { "ExceptIfAttachmentIsPasswordProtected", n => { ExceptIfAttachmentIsPasswordProtected = n.GetStringValue(); } },
                { "ExceptIfAttachmentIsUnsupported", n => { ExceptIfAttachmentIsUnsupported = n.GetStringValue(); } },
                { "ExceptIfAttachmentMatchesPatterns", n => { ExceptIfAttachmentMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfAttachmentNameMatchesPatterns", n => { ExceptIfAttachmentNameMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfAttachmentProcessingLimitExceeded", n => { ExceptIfAttachmentProcessingLimitExceeded = n.GetStringValue(); } },
                { "ExceptIfAttachmentPropertyContainsWords", n => { ExceptIfAttachmentPropertyContainsWords = n.GetStringValue(); } },
                { "ExceptIfAttachmentSizeOver", n => { ExceptIfAttachmentSizeOver = n.GetStringValue(); } },
                { "ExceptIfFrom", n => { ExceptIfFrom = n.GetStringValue(); } },
                { "ExceptIfFromAddressContainsWords", n => { ExceptIfFromAddressContainsWords = n.GetStringValue(); } },
                { "ExceptIfFromAddressMatchesPatterns", n => { ExceptIfFromAddressMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfFromMemberOf", n => { ExceptIfFromMemberOf = n.GetStringValue(); } },
                { "ExceptIfFromScope", n => { ExceptIfFromScope = n.GetStringValue(); } },
                { "ExceptIfHeaderContainsWords", n => { ExceptIfHeaderContainsWords = n.GetStringValue(); } },
                { "ExceptIfHeaderContainsWordsMessageHeader", n => { ExceptIfHeaderContainsWordsMessageHeader = n.GetStringValue(); } },
                { "ExceptIfHeaderMatchesPatterns", n => { ExceptIfHeaderMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfHeaderMatchesPatternsMessageHeader", n => { ExceptIfHeaderMatchesPatternsMessageHeader = n.GetStringValue(); } },
                { "ExceptIfMessageSizeOver", n => { ExceptIfMessageSizeOver = n.GetStringValue(); } },
                { "ExceptIfMessageTypeMatches", n => { ExceptIfMessageTypeMatches = n.GetStringValue(); } },
                { "ExceptIfRecipientAddressContainsWords", n => { ExceptIfRecipientAddressContainsWords = n.GetStringValue(); } },
                { "ExceptIfRecipientAddressMatchesPatterns", n => { ExceptIfRecipientAddressMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfRecipientDomainIs", n => { ExceptIfRecipientDomainIs = n.GetStringValue(); } },
                { "ExceptIfSCLOver", n => { ExceptIfSCLOver = n.GetStringValue(); } },
                { "ExceptIfSenderDomainIs", n => { ExceptIfSenderDomainIs = n.GetStringValue(); } },
                { "ExceptIfSenderIpRanges", n => { ExceptIfSenderIpRanges = n.GetStringValue(); } },
                { "ExceptIfSentTo", n => { ExceptIfSentTo = n.GetStringValue(); } },
                { "ExceptIfSentToMemberOf", n => { ExceptIfSentToMemberOf = n.GetStringValue(); } },
                { "ExceptIfSentToScope", n => { ExceptIfSentToScope = n.GetStringValue(); } },
                { "ExceptIfSubjectContainsWords", n => { ExceptIfSubjectContainsWords = n.GetStringValue(); } },
                { "ExceptIfSubjectMatchesPatterns", n => { ExceptIfSubjectMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfSubjectOrBodyContainsWords", n => { ExceptIfSubjectOrBodyContainsWords = n.GetStringValue(); } },
                { "ExceptIfSubjectOrBodyMatchesPatterns", n => { ExceptIfSubjectOrBodyMatchesPatterns = n.GetStringValue(); } },
                { "ExceptIfWithImportance", n => { ExceptIfWithImportance = n.GetStringValue(); } },
                { "exceptionType", n => { ExceptionType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ExpiryDate", n => { ExpiryDate = n.GetDateTimeOffsetValue(); } },
                { "From", n => { From = n.GetStringValue(); } },
                { "FromAddressContainsWords", n => { FromAddressContainsWords = n.GetStringValue(); } },
                { "FromAddressMatchesPatterns", n => { FromAddressMatchesPatterns = n.GetStringValue(); } },
                { "FromMemberOf", n => { FromMemberOf = n.GetStringValue(); } },
                { "FromScope", n => { FromScope = n.GetStringValue(); } },
                { "GenerateIncidentReport", n => { GenerateIncidentReport = n.GetStringValue(); } },
                { "GenerateNotification", n => { GenerateNotification = n.GetStringValue(); } },
                { "HeaderContainsWords", n => { HeaderContainsWords = n.GetStringValue(); } },
                { "HeaderContainsWordsMessageHeader", n => { HeaderContainsWordsMessageHeader = n.GetStringValue(); } },
                { "HeaderMatchesPatterns", n => { HeaderMatchesPatterns = n.GetStringValue(); } },
                { "HeaderMatchesPatternsMessageHeader", n => { HeaderMatchesPatternsMessageHeader = n.GetStringValue(); } },
                { "IncidentReportContent", n => { IncidentReportContent = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MessageSizeOver", n => { MessageSizeOver = n.GetStringValue(); } },
                { "MessageTypeMatches", n => { MessageTypeMatches = n.GetStringValue(); } },
                { "Mode", n => { Mode = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "ModerateMessageByManager", n => { ModerateMessageByManager = n.GetStringValue(); } },
                { "ModerateMessageByUser", n => { ModerateMessageByUser = n.GetStringValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "PrependSubject", n => { PrependSubject = n.GetStringValue(); } },
                { "Priority", n => { Priority = n.GetDoubleValue(); } },
                { "Quarantine", n => { Quarantine = n.GetStringValue(); } },
                { "RecipientAddressContainsWords", n => { RecipientAddressContainsWords = n.GetStringValue(); } },
                { "RecipientAddressMatchesPatterns", n => { RecipientAddressMatchesPatterns = n.GetStringValue(); } },
                { "RecipientDomainIs", n => { RecipientDomainIs = n.GetStringValue(); } },
                { "RedirectMessageTo", n => { RedirectMessageTo = n.GetStringValue(); } },
                { "RejectMessageEnhancedStatusCode", n => { RejectMessageEnhancedStatusCode = n.GetStringValue(); } },
                { "RejectMessageReasonText", n => { RejectMessageReasonText = n.GetStringValue(); } },
                { "RemoveHeader", n => { RemoveHeader = n.GetStringValue(); } },
                { "RouteMessageOutboundConnector", n => { RouteMessageOutboundConnector = n.GetStringValue(); } },
                { "ruleId", n => { RuleId = n.GetStringValue(); } },
                { "SCLOver", n => { SCLOver = n.GetStringValue(); } },
                { "SenderAddressLocation", n => { SenderAddressLocation = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "SenderDomainIs", n => { SenderDomainIs = n.GetStringValue(); } },
                { "SenderIpRanges", n => { SenderIpRanges = n.GetStringValue(); } },
                { "SentTo", n => { SentTo = n.GetStringValue(); } },
                { "SentToMemberOf", n => { SentToMemberOf = n.GetStringValue(); } },
                { "SentToScope", n => { SentToScope = n.GetStringValue(); } },
                { "SetAuditSeverity", n => { SetAuditSeverity = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "SetHeaderName", n => { SetHeaderName = n.GetStringValue(); } },
                { "SetHeaderValue", n => { SetHeaderValue = n.GetStringValue(); } },
                { "SetSCL", n => { SetSCL = n.GetStringValue(); } },
                { "State", n => { State = n.GetStringValue(); } },
                { "StopRuleProcessing", n => { StopRuleProcessing = n.GetBoolValue(); } },
                { "SubjectContainsWords", n => { SubjectContainsWords = n.GetStringValue(); } },
                { "SubjectMatchesPatterns", n => { SubjectMatchesPatterns = n.GetStringValue(); } },
                { "SubjectOrBodyContainsWords", n => { SubjectOrBodyContainsWords = n.GetStringValue(); } },
                { "SubjectOrBodyMatchesPatterns", n => { SubjectOrBodyMatchesPatterns = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "WithImportance", n => { WithImportance = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("actionType", ActionType);
            writer.WriteDateTimeOffsetValue("ActivationDate", ActivationDate);
            writer.WriteStringValue("AnyOfCcHeader", AnyOfCcHeader);
            writer.WriteStringValue("AnyOfCcHeaderMemberOf", AnyOfCcHeaderMemberOf);
            writer.WriteStringValue("AnyOfRecipientAddressContainsWords", AnyOfRecipientAddressContainsWords);
            writer.WriteStringValue("AnyOfRecipientAddressMatchesPatterns", AnyOfRecipientAddressMatchesPatterns);
            writer.WriteStringValue("AnyOfToCcHeader", AnyOfToCcHeader);
            writer.WriteStringValue("AnyOfToCcHeaderMemberOf", AnyOfToCcHeaderMemberOf);
            writer.WriteStringValue("AnyOfToHeader", AnyOfToHeader);
            writer.WriteStringValue("AnyOfToHeaderMemberOf", AnyOfToHeaderMemberOf);
            writer.WriteStringValue("ApplyClassification", ApplyClassification);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("ApplyHtmlDisclaimerFallbackAction", ApplyHtmlDisclaimerFallbackAction);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("ApplyHtmlDisclaimerLocation", ApplyHtmlDisclaimerLocation);
            writer.WriteStringValue("ApplyHtmlDisclaimerText", ApplyHtmlDisclaimerText);
            writer.WriteStringValue("ApplyOME", ApplyOME);
            writer.WriteBoolValue("applyToAllMessages", ApplyToAllMessages);
            writer.WriteStringValue("AttachmentContainsWords", AttachmentContainsWords);
            writer.WriteStringValue("AttachmentExtensionMatchesWords", AttachmentExtensionMatchesWords);
            writer.WriteStringValue("AttachmentHasExecutableContent", AttachmentHasExecutableContent);
            writer.WriteStringValue("AttachmentIsPasswordProtected", AttachmentIsPasswordProtected);
            writer.WriteStringValue("AttachmentIsUnsupported", AttachmentIsUnsupported);
            writer.WriteStringValue("AttachmentMatchesPatterns", AttachmentMatchesPatterns);
            writer.WriteStringValue("AttachmentNameMatchesPatterns", AttachmentNameMatchesPatterns);
            writer.WriteStringValue("AttachmentProcessingLimitExceeded", AttachmentProcessingLimitExceeded);
            writer.WriteStringValue("AttachmentPropertyContainsWords", AttachmentPropertyContainsWords);
            writer.WriteStringValue("AttachmentSizeOver", AttachmentSizeOver);
            writer.WriteStringValue("BlindCopyTo", BlindCopyTo);
            writer.WriteStringValue("Comments", Comments);
            writer.WriteCollectionOfPrimitiveValues<string>("conditionType", ConditionType);
            writer.WriteStringValue("CopyTo", CopyTo);
            writer.WriteStringValue("Count", Count);
            writer.WriteStringValue("DeleteMessage", DeleteMessage);
            writer.WriteBoolValue("Enabled", Enabled);
            writer.WriteStringValue("ExceptIfAnyOfCcHeader", ExceptIfAnyOfCcHeader);
            writer.WriteStringValue("ExceptIfAnyOfCcHeaderMemberOf", ExceptIfAnyOfCcHeaderMemberOf);
            writer.WriteStringValue("ExceptIfAnyOfRecipientAddressContainsWords", ExceptIfAnyOfRecipientAddressContainsWords);
            writer.WriteStringValue("ExceptIfAnyOfRecipientAddressMatchesPatterns", ExceptIfAnyOfRecipientAddressMatchesPatterns);
            writer.WriteStringValue("ExceptIfAnyOfToCcHeader", ExceptIfAnyOfToCcHeader);
            writer.WriteStringValue("ExceptIfAnyOfToCcHeaderMemberOf", ExceptIfAnyOfToCcHeaderMemberOf);
            writer.WriteStringValue("ExceptIfAnyOfToHeader", ExceptIfAnyOfToHeader);
            writer.WriteStringValue("ExceptIfAnyOfToHeaderMemberOf", ExceptIfAnyOfToHeaderMemberOf);
            writer.WriteStringValue("ExceptIfAttachmentContainsWords", ExceptIfAttachmentContainsWords);
            writer.WriteStringValue("ExceptIfAttachmentExtensionMatchesWords", ExceptIfAttachmentExtensionMatchesWords);
            writer.WriteStringValue("ExceptIfAttachmentHasExecutableContent", ExceptIfAttachmentHasExecutableContent);
            writer.WriteStringValue("ExceptIfAttachmentIsPasswordProtected", ExceptIfAttachmentIsPasswordProtected);
            writer.WriteStringValue("ExceptIfAttachmentIsUnsupported", ExceptIfAttachmentIsUnsupported);
            writer.WriteStringValue("ExceptIfAttachmentMatchesPatterns", ExceptIfAttachmentMatchesPatterns);
            writer.WriteStringValue("ExceptIfAttachmentNameMatchesPatterns", ExceptIfAttachmentNameMatchesPatterns);
            writer.WriteStringValue("ExceptIfAttachmentProcessingLimitExceeded", ExceptIfAttachmentProcessingLimitExceeded);
            writer.WriteStringValue("ExceptIfAttachmentPropertyContainsWords", ExceptIfAttachmentPropertyContainsWords);
            writer.WriteStringValue("ExceptIfAttachmentSizeOver", ExceptIfAttachmentSizeOver);
            writer.WriteStringValue("ExceptIfFrom", ExceptIfFrom);
            writer.WriteStringValue("ExceptIfFromAddressContainsWords", ExceptIfFromAddressContainsWords);
            writer.WriteStringValue("ExceptIfFromAddressMatchesPatterns", ExceptIfFromAddressMatchesPatterns);
            writer.WriteStringValue("ExceptIfFromMemberOf", ExceptIfFromMemberOf);
            writer.WriteStringValue("ExceptIfFromScope", ExceptIfFromScope);
            writer.WriteStringValue("ExceptIfHeaderContainsWords", ExceptIfHeaderContainsWords);
            writer.WriteStringValue("ExceptIfHeaderContainsWordsMessageHeader", ExceptIfHeaderContainsWordsMessageHeader);
            writer.WriteStringValue("ExceptIfHeaderMatchesPatterns", ExceptIfHeaderMatchesPatterns);
            writer.WriteStringValue("ExceptIfHeaderMatchesPatternsMessageHeader", ExceptIfHeaderMatchesPatternsMessageHeader);
            writer.WriteStringValue("ExceptIfMessageSizeOver", ExceptIfMessageSizeOver);
            writer.WriteStringValue("ExceptIfMessageTypeMatches", ExceptIfMessageTypeMatches);
            writer.WriteStringValue("ExceptIfRecipientAddressContainsWords", ExceptIfRecipientAddressContainsWords);
            writer.WriteStringValue("ExceptIfRecipientAddressMatchesPatterns", ExceptIfRecipientAddressMatchesPatterns);
            writer.WriteStringValue("ExceptIfRecipientDomainIs", ExceptIfRecipientDomainIs);
            writer.WriteStringValue("ExceptIfSCLOver", ExceptIfSCLOver);
            writer.WriteStringValue("ExceptIfSenderDomainIs", ExceptIfSenderDomainIs);
            writer.WriteStringValue("ExceptIfSenderIpRanges", ExceptIfSenderIpRanges);
            writer.WriteStringValue("ExceptIfSentTo", ExceptIfSentTo);
            writer.WriteStringValue("ExceptIfSentToMemberOf", ExceptIfSentToMemberOf);
            writer.WriteStringValue("ExceptIfSentToScope", ExceptIfSentToScope);
            writer.WriteStringValue("ExceptIfSubjectContainsWords", ExceptIfSubjectContainsWords);
            writer.WriteStringValue("ExceptIfSubjectMatchesPatterns", ExceptIfSubjectMatchesPatterns);
            writer.WriteStringValue("ExceptIfSubjectOrBodyContainsWords", ExceptIfSubjectOrBodyContainsWords);
            writer.WriteStringValue("ExceptIfSubjectOrBodyMatchesPatterns", ExceptIfSubjectOrBodyMatchesPatterns);
            writer.WriteStringValue("ExceptIfWithImportance", ExceptIfWithImportance);
            writer.WriteCollectionOfPrimitiveValues<string>("exceptionType", ExceptionType);
            writer.WriteDateTimeOffsetValue("ExpiryDate", ExpiryDate);
            writer.WriteStringValue("From", From);
            writer.WriteStringValue("FromAddressContainsWords", FromAddressContainsWords);
            writer.WriteStringValue("FromAddressMatchesPatterns", FromAddressMatchesPatterns);
            writer.WriteStringValue("FromMemberOf", FromMemberOf);
            writer.WriteStringValue("FromScope", FromScope);
            writer.WriteStringValue("GenerateIncidentReport", GenerateIncidentReport);
            writer.WriteStringValue("GenerateNotification", GenerateNotification);
            writer.WriteStringValue("HeaderContainsWords", HeaderContainsWords);
            writer.WriteStringValue("HeaderContainsWordsMessageHeader", HeaderContainsWordsMessageHeader);
            writer.WriteStringValue("HeaderMatchesPatterns", HeaderMatchesPatterns);
            writer.WriteStringValue("HeaderMatchesPatternsMessageHeader", HeaderMatchesPatternsMessageHeader);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("IncidentReportContent", IncidentReportContent);
            writer.WriteStringValue("MessageSizeOver", MessageSizeOver);
            writer.WriteStringValue("MessageTypeMatches", MessageTypeMatches);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("Mode", Mode);
            writer.WriteStringValue("ModerateMessageByManager", ModerateMessageByManager);
            writer.WriteStringValue("ModerateMessageByUser", ModerateMessageByUser);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("PrependSubject", PrependSubject);
            writer.WriteDoubleValue("Priority", Priority);
            writer.WriteStringValue("Quarantine", Quarantine);
            writer.WriteStringValue("RecipientAddressContainsWords", RecipientAddressContainsWords);
            writer.WriteStringValue("RecipientAddressMatchesPatterns", RecipientAddressMatchesPatterns);
            writer.WriteStringValue("RecipientDomainIs", RecipientDomainIs);
            writer.WriteStringValue("RedirectMessageTo", RedirectMessageTo);
            writer.WriteStringValue("RejectMessageEnhancedStatusCode", RejectMessageEnhancedStatusCode);
            writer.WriteStringValue("RejectMessageReasonText", RejectMessageReasonText);
            writer.WriteStringValue("RemoveHeader", RemoveHeader);
            writer.WriteStringValue("RouteMessageOutboundConnector", RouteMessageOutboundConnector);
            writer.WriteStringValue("ruleId", RuleId);
            writer.WriteStringValue("SCLOver", SCLOver);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("SenderAddressLocation", SenderAddressLocation);
            writer.WriteStringValue("SenderDomainIs", SenderDomainIs);
            writer.WriteStringValue("SenderIpRanges", SenderIpRanges);
            writer.WriteStringValue("SentTo", SentTo);
            writer.WriteStringValue("SentToMemberOf", SentToMemberOf);
            writer.WriteStringValue("SentToScope", SentToScope);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("SetAuditSeverity", SetAuditSeverity);
            writer.WriteStringValue("SetHeaderName", SetHeaderName);
            writer.WriteStringValue("SetHeaderValue", SetHeaderValue);
            writer.WriteStringValue("SetSCL", SetSCL);
            writer.WriteStringValue("State", State);
            writer.WriteBoolValue("StopRuleProcessing", StopRuleProcessing);
            writer.WriteStringValue("SubjectContainsWords", SubjectContainsWords);
            writer.WriteStringValue("SubjectMatchesPatterns", SubjectMatchesPatterns);
            writer.WriteStringValue("SubjectOrBodyContainsWords", SubjectOrBodyContainsWords);
            writer.WriteStringValue("SubjectOrBodyMatchesPatterns", SubjectOrBodyMatchesPatterns);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("value", Value);
            writer.WriteStringValue("WithImportance", WithImportance);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
