// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.EditUser
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EditUserPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Body parameter from PS1: AddedAliases</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddedAliases { get; set; }
#nullable restore
#else
        public string AddedAliases { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>(auto) from CippAddEditUser.jsx (array of LabelValue)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddToGroups { get; set; }
#nullable restore
#else
        public List<string> AddToGroups { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
        public bool? Autopassword { get; set; }
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessPhones { get; set; }
#nullable restore
#else
        public string BusinessPhones { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>Body parameter from PS1: CopyFrom</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CopyFrom { get; set; }
#nullable restore
#else
        public string CopyFrom { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomData { get; set; }
#nullable restore
#else
        public string CustomData { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultAttributes { get; set; }
#nullable restore
#else
        public string DefaultAttributes { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Department { get; set; }
#nullable restore
#else
        public string Department { get; set; }
#endif
        /// <summary>Body parameter from PS1: DisplayName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EditUserPatchRequestBodyPostExecution { get; set; }
#nullable restore
#else
        public string EditUserPatchRequestBodyPostExecution { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobTitle { get; set; }
#nullable restore
#else
        public string JobTitle { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Licenses { get; set; }
#nullable restore
#else
        public List<string> Licenses { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailNickname { get; set; }
#nullable restore
#else
        public string MailNickname { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobilePhone { get; set; }
#nullable restore
#else
        public string MobilePhone { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
        public bool? MustChangePass { get; set; }
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtherMails { get; set; }
#nullable restore
#else
        public string OtherMails { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The postExecution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_postExecution? PostExecution { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_postExecution PostExecution { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_primDomain? PrimDomain { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_primDomain PrimDomain { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx (array of LabelValue)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveFromGroups { get; set; }
#nullable restore
#else
        public List<string> RemoveFromGroups { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
        public bool? RemoveLicenses { get; set; }
        /// <summary>The Scheduled property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_Scheduled? Scheduled { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_Scheduled Scheduled { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SetManager { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SetManager { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SetSponsor { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SetSponsor { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
        public bool? Sherweb { get; set; }
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_sherwebLicense? SherwebLicense { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_sherwebLicense SherwebLicense { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetAddress { get; set; }
#nullable restore
#else
        public string StreetAddress { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Surname { get; set; }
#nullable restore
#else
        public string Surname { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_usageLocation? UsageLocation { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_usageLocation UsageLocation { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>(auto) from API scan</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPrincipalName { get; set; }
#nullable restore
#else
        public string UserPrincipalName { get; set; }
#endif
        /// <summary>(auto) from CippAddEditUser.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? UserTemplate { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue UserTemplate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody"/> and sets the default values.
        /// </summary>
        public EditUserPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddToGroups", n => { AddToGroups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "AddedAliases", n => { AddedAliases = n.GetStringValue(); } },
                { "Autopassword", n => { Autopassword = n.GetBoolValue(); } },
                { "businessPhones", n => { BusinessPhones = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "CopyFrom", n => { CopyFrom = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "customData", n => { CustomData = n.GetStringValue(); } },
                { "defaultAttributes", n => { DefaultAttributes = n.GetStringValue(); } },
                { "department", n => { Department = n.GetStringValue(); } },
                { "DisplayName", n => { DisplayName = n.GetStringValue(); } },
                { "Domain", n => { Domain = n.GetStringValue(); } },
                { "PostExecution", n => { EditUserPatchRequestBodyPostExecution = n.GetStringValue(); } },
                { "givenName", n => { GivenName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "jobTitle", n => { JobTitle = n.GetStringValue(); } },
                { "licenses", n => { Licenses = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mailNickname", n => { MailNickname = n.GetStringValue(); } },
                { "mobilePhone", n => { MobilePhone = n.GetStringValue(); } },
                { "MustChangePass", n => { MustChangePass = n.GetBoolValue(); } },
                { "otherMails", n => { OtherMails = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "postExecution", n => { PostExecution = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_postExecution>(global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_postExecution.CreateFromDiscriminatorValue); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "primDomain", n => { PrimDomain = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_primDomain>(global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_primDomain.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "RemoveFromGroups", n => { RemoveFromGroups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "removeLicenses", n => { RemoveLicenses = n.GetBoolValue(); } },
                { "Scheduled", n => { Scheduled = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_Scheduled>(global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_Scheduled.CreateFromDiscriminatorValue); } },
                { "setManager", n => { SetManager = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "setSponsor", n => { SetSponsor = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "sherweb", n => { Sherweb = n.GetBoolValue(); } },
                { "sherwebLicense", n => { SherwebLicense = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_sherwebLicense>(global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_sherwebLicense.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "streetAddress", n => { StreetAddress = n.GetStringValue(); } },
                { "surname", n => { Surname = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "usageLocation", n => { UsageLocation = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_usageLocation>(global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_usageLocation.CreateFromDiscriminatorValue); } },
                { "userPrincipalName", n => { UserPrincipalName = n.GetStringValue(); } },
                { "userTemplate", n => { UserTemplate = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AddedAliases", AddedAliases);
            writer.WriteCollectionOfPrimitiveValues<string>("AddToGroups", AddToGroups);
            writer.WriteBoolValue("Autopassword", Autopassword);
            writer.WriteStringValue("businessPhones", BusinessPhones);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteStringValue("CopyFrom", CopyFrom);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("customData", CustomData);
            writer.WriteStringValue("defaultAttributes", DefaultAttributes);
            writer.WriteStringValue("department", Department);
            writer.WriteStringValue("DisplayName", DisplayName);
            writer.WriteStringValue("Domain", Domain);
            writer.WriteStringValue("PostExecution", EditUserPatchRequestBodyPostExecution);
            writer.WriteStringValue("givenName", GivenName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("jobTitle", JobTitle);
            writer.WriteCollectionOfPrimitiveValues<string>("licenses", Licenses);
            writer.WriteStringValue("mailNickname", MailNickname);
            writer.WriteStringValue("mobilePhone", MobilePhone);
            writer.WriteBoolValue("MustChangePass", MustChangePass);
            writer.WriteStringValue("otherMails", OtherMails);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_postExecution>("postExecution", PostExecution);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_primDomain>("primDomain", PrimDomain);
            writer.WriteStringValue("reference", Reference);
            writer.WriteCollectionOfPrimitiveValues<string>("RemoveFromGroups", RemoveFromGroups);
            writer.WriteBoolValue("removeLicenses", RemoveLicenses);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_Scheduled>("Scheduled", Scheduled);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("setManager", SetManager);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("setSponsor", SetSponsor);
            writer.WriteBoolValue("sherweb", Sherweb);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_sherwebLicense>("sherwebLicense", SherwebLicense);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("streetAddress", StreetAddress);
            writer.WriteStringValue("surname", Surname);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditUser.EditUserPatchRequestBody_usageLocation>("usageLocation", UsageLocation);
            writer.WriteStringValue("username", Username);
            writer.WriteStringValue("userPrincipalName", UserPrincipalName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("userTemplate", UserTemplate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
