// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecAssignPolicy
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecAssignPolicyPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AssignmentFilterName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentFilterName { get; set; }
#nullable restore
#else
        public string AssignmentFilterName { get; set; }
#endif
        /// <summary>The AssignmentFilterType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentFilterType { get; set; }
#nullable restore
#else
        public string AssignmentFilterType { get; set; }
#endif
        /// <summary>The assignmentMode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentMode { get; set; }
#nullable restore
#else
        public string AssignmentMode { get; set; }
#endif
        /// <summary>The AssignTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignTo { get; set; }
#nullable restore
#else
        public string AssignTo { get; set; }
#endif
        /// <summary>The excludeGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExcludeGroup { get; set; }
#nullable restore
#else
        public string ExcludeGroup { get; set; }
#endif
        /// <summary>The GroupIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupIds { get; set; }
#nullable restore
#else
        public string GroupIds { get; set; }
#endif
        /// <summary>The GroupNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupNames { get; set; }
#nullable restore
#else
        public string GroupNames { get; set; }
#endif
        /// <summary>The ID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ID { get; set; }
#nullable restore
#else
        public string ID { get; set; }
#endif
        /// <summary>The platformType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlatformType { get; set; }
#nullable restore
#else
        public string PlatformType { get; set; }
#endif
        /// <summary>The tenantFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>The Type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecAssignPolicy.ExecAssignPolicyPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExecAssignPolicyPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecAssignPolicy.ExecAssignPolicyPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecAssignPolicy.ExecAssignPolicyPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecAssignPolicy.ExecAssignPolicyPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AssignTo", n => { AssignTo = n.GetStringValue(); } },
                { "AssignmentFilterName", n => { AssignmentFilterName = n.GetStringValue(); } },
                { "AssignmentFilterType", n => { AssignmentFilterType = n.GetStringValue(); } },
                { "assignmentMode", n => { AssignmentMode = n.GetStringValue(); } },
                { "excludeGroup", n => { ExcludeGroup = n.GetStringValue(); } },
                { "GroupIds", n => { GroupIds = n.GetStringValue(); } },
                { "GroupNames", n => { GroupNames = n.GetStringValue(); } },
                { "ID", n => { ID = n.GetStringValue(); } },
                { "platformType", n => { PlatformType = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "Type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AssignmentFilterName", AssignmentFilterName);
            writer.WriteStringValue("AssignmentFilterType", AssignmentFilterType);
            writer.WriteStringValue("assignmentMode", AssignmentMode);
            writer.WriteStringValue("AssignTo", AssignTo);
            writer.WriteStringValue("excludeGroup", ExcludeGroup);
            writer.WriteStringValue("GroupIds", GroupIds);
            writer.WriteStringValue("GroupNames", GroupNames);
            writer.WriteStringValue("ID", ID);
            writer.WriteStringValue("platformType", PlatformType);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("Type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
