// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddDefenderDeployment
{
    /// <summary>
    /// Compliance parameter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddDefenderDeploymentPostRequestBody_Compliance : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Compliance.AllowMEMEnforceCompliance parameter</summary>
        public bool? AllowMEMEnforceCompliance { get; set; }
        /// <summary>Compliance.AppSync parameter</summary>
        public bool? AppSync { get; set; }
        /// <summary>Compliance.BlockunsupportedOS parameter</summary>
        public bool? BlockunsupportedOS { get; set; }
        /// <summary>Compliance.ConnectAndroid parameter</summary>
        public bool? ConnectAndroid { get; set; }
        /// <summary>Compliance.ConnectAndroidCompliance parameter</summary>
        public bool? ConnectAndroidCompliance { get; set; }
        /// <summary>Compliance.ConnectIos parameter</summary>
        public bool? ConnectIos { get; set; }
        /// <summary>Compliance.ConnectIosCompliance parameter</summary>
        public bool? ConnectIosCompliance { get; set; }
        /// <summary>Compliance.ConnectWindows parameter</summary>
        public bool? ConnectWindows { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddDefenderDeployment.AddDefenderDeploymentPostRequestBody_Compliance"/> and sets the default values.
        /// </summary>
        public AddDefenderDeploymentPostRequestBody_Compliance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddDefenderDeployment.AddDefenderDeploymentPostRequestBody_Compliance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddDefenderDeployment.AddDefenderDeploymentPostRequestBody_Compliance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddDefenderDeployment.AddDefenderDeploymentPostRequestBody_Compliance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AllowMEMEnforceCompliance", n => { AllowMEMEnforceCompliance = n.GetBoolValue(); } },
                { "AppSync", n => { AppSync = n.GetBoolValue(); } },
                { "BlockunsupportedOS", n => { BlockunsupportedOS = n.GetBoolValue(); } },
                { "ConnectAndroid", n => { ConnectAndroid = n.GetBoolValue(); } },
                { "ConnectAndroidCompliance", n => { ConnectAndroidCompliance = n.GetBoolValue(); } },
                { "ConnectIos", n => { ConnectIos = n.GetBoolValue(); } },
                { "ConnectIosCompliance", n => { ConnectIosCompliance = n.GetBoolValue(); } },
                { "ConnectWindows", n => { ConnectWindows = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AllowMEMEnforceCompliance", AllowMEMEnforceCompliance);
            writer.WriteBoolValue("AppSync", AppSync);
            writer.WriteBoolValue("BlockunsupportedOS", BlockunsupportedOS);
            writer.WriteBoolValue("ConnectAndroid", ConnectAndroid);
            writer.WriteBoolValue("ConnectAndroidCompliance", ConnectAndroidCompliance);
            writer.WriteBoolValue("ConnectIos", ConnectIos);
            writer.WriteBoolValue("ConnectIosCompliance", ConnectIosCompliance);
            writer.WriteBoolValue("ConnectWindows", ConnectWindows);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
