// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.CIPP.Client.Api.AddAssignmentFilter
{
    /// <summary>(auto) from CippAddAssignmentFilterForm.jsx</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddAssignmentFilterPostRequestBody_assignmentFilterManagementType
    {
        [EnumMember(Value = "devices")]
        #pragma warning disable CS1591
        Devices,
        #pragma warning restore CS1591
        [EnumMember(Value = "apps")]
        #pragma warning disable CS1591
        Apps,
        #pragma warning restore CS1591
    }
}
