// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.CIPP.Client.Api.GetVersion
{
    /// <summary>
    /// Builds and executes requests for operations under \api\GetVersion
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetVersionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVersionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/GetVersion{?LocalVersion*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetVersionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/GetVersion{?LocalVersion*}", rawUrl)
        {
        }
        /// <summary>
        /// GetVersion
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Models.StandardResults"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults?> GetAsync(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder.GetVersionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults> GetAsync(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder.GetVersionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.CIPP.Client.Models.StandardResults>(requestInfo, global::Bezalu.CIPP.Client.Models.StandardResults.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// GetVersion
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder.GetVersionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder.GetVersionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// GetVersion
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVersionRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? LocalVersion { get; set; }
#nullable restore
#else
            public string LocalVersion { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetVersionRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.CIPP.Client.Api.GetVersion.GetVersionRequestBuilder.GetVersionRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
