// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.CIPP.Client.Api.ExecSetSecurityIncident
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ExecSetSecurityIncident
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecSetSecurityIncidentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecSetSecurityIncidentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ExecSetSecurityIncident?tenantFilter={tenantFilter}{&Assigned*,Classification*,Determination*,GUID*,Redirected*,Status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecSetSecurityIncidentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ExecSetSecurityIncident?tenantFilter={tenantFilter}{&Assigned*,Classification*,Determination*,GUID*,Redirected*,Status*}", rawUrl)
        {
        }
        /// <summary>
        /// ExecSetSecurityIncident
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Models.StandardResults"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults?> PostAsync(global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentPostRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder.ExecSetSecurityIncidentRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults> PostAsync(global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentPostRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder.ExecSetSecurityIncidentRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.CIPP.Client.Models.StandardResults>(requestInfo, global::Bezalu.CIPP.Client.Models.StandardResults.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ExecSetSecurityIncident
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentPostRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder.ExecSetSecurityIncidentRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentPostRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder.ExecSetSecurityIncidentRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ExecSetSecurityIncident
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecSetSecurityIncidentRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Assigned { get; set; }
#nullable restore
#else
            public string Assigned { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Classification { get; set; }
#nullable restore
#else
            public string Classification { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Determination { get; set; }
#nullable restore
#else
            public string Determination { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? GUID { get; set; }
#nullable restore
#else
            public string GUID { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Redirected { get; set; }
#nullable restore
#else
            public string Redirected { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Status { get; set; }
#nullable restore
#else
            public string Status { get; set; }
#endif
            /// <summary>Target tenant domain or &apos;AllTenants&apos; for multi-tenant operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tenantFilter")]
            public string? TenantFilter { get; set; }
#nullable restore
#else
            [QueryParameter("tenantFilter")]
            public string TenantFilter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecSetSecurityIncidentRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Bezalu.CIPP.Client.Api.ExecSetSecurityIncident.ExecSetSecurityIncidentRequestBuilder.ExecSetSecurityIncidentRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
