// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddTenantAllowBlockListTemplate
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddTenantAllowBlockListTemplatePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Entries { get; set; }
#nullable restore
#else
        public string Entries { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ListMethod { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ListMethod { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ListType { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ListType { get; set; }
#endif
        /// <summary>The NoExpiration property</summary>
        public bool? NoExpiration { get; set; }
        /// <summary>The notes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The RemoveAfter property</summary>
        public bool? RemoveAfter { get; set; }
        /// <summary>The templateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddTenantAllowBlockListTemplate.AddTenantAllowBlockListTemplatePostRequestBody"/> and sets the default values.
        /// </summary>
        public AddTenantAllowBlockListTemplatePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddTenantAllowBlockListTemplate.AddTenantAllowBlockListTemplatePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddTenantAllowBlockListTemplate.AddTenantAllowBlockListTemplatePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddTenantAllowBlockListTemplate.AddTenantAllowBlockListTemplatePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entries", n => { Entries = n.GetStringValue(); } },
                { "listMethod", n => { ListMethod = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "listType", n => { ListType = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "NoExpiration", n => { NoExpiration = n.GetBoolValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "RemoveAfter", n => { RemoveAfter = n.GetBoolValue(); } },
                { "templateName", n => { TemplateName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("entries", Entries);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("listMethod", ListMethod);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("listType", ListType);
            writer.WriteBoolValue("NoExpiration", NoExpiration);
            writer.WriteStringValue("notes", Notes);
            writer.WriteBoolValue("RemoveAfter", RemoveAfter);
            writer.WriteStringValue("templateName", TemplateName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
