// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.EditContact
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EditContactPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Formatter maps &apos;city&apos; → &apos;City&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>Formatter maps &apos;companyName&apos; → &apos;Company&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>Graph contact id; read from API response. PS1 uses as Identity for Set-Contact/Set-MailContact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactID { get; set; }
#nullable restore
#else
        public string ContactID { get; set; }
#endif
        /// <summary>Formatter maps &apos;country&apos; autocomplete → &apos;CountryOrRegion&apos; (unwraps .value).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryOrRegion { get; set; }
#nullable restore
#else
        public string CountryOrRegion { get; set; }
#endif
        /// <summary>Sent as lowercase &apos;displayName&apos;; PS1 maps to &apos;DisplayName&apos; parameter of Set-Contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>PS1 maps to WindowsEmailAddress on Set-Contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>PS1 maps to FirstName.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>PS1 uses as HiddenFromAddressListsEnabled on Set-MailContact.</summary>
        public bool? HidefromGAL { get; set; }
        /// <summary>NOTE: formatter sends form field &apos;lastName&apos; as-is but PS1 reads $contactInfo.LastName (capital L). Matches because object property access is case-insensitive in PS.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>PS1 maps to MailTip on Set-MailContact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailTip { get; set; }
#nullable restore
#else
        public string MailTip { get; set; }
#endif
        /// <summary>PS1 maps to MobilePhone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobilePhone { get; set; }
#nullable restore
#else
        public string MobilePhone { get; set; }
#endif
        /// <summary>Formatter maps &apos;businessPhone&apos; → &apos;phone&apos;. PS1 maps to Phone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Formatter maps &apos;postalCode&apos; → &apos;PostalCode&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>Formatter maps &apos;state&apos; → &apos;State&apos;. PS1 maps to StateOrProvince.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Formatter maps &apos;streetAddress&apos; → &apos;StreetAddress&apos;. PS1 reads $contactInfo.StreetAddress.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetAddress { get; set; }
#nullable restore
#else
        public string StreetAddress { get; set; }
#endif
        /// <summary>Tenant domain/ID. Formatter reads from useSettings().currentTenant and sends as &apos;tenantID&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantID { get; set; }
#nullable restore
#else
        public string TenantID { get; set; }
#endif
        /// <summary>Formatter maps form &apos;jobTitle&apos; → body field &apos;Title&apos;. PS1 reads $contactInfo.Title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>PS1 maps to WebPage.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.EditContact.EditContactPostRequestBody"/> and sets the default values.
        /// </summary>
        public EditContactPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.EditContact.EditContactPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.EditContact.EditContactPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.EditContact.EditContactPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "City", n => { City = n.GetStringValue(); } },
                { "Company", n => { Company = n.GetStringValue(); } },
                { "ContactID", n => { ContactID = n.GetStringValue(); } },
                { "CountryOrRegion", n => { CountryOrRegion = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "hidefromGAL", n => { HidefromGAL = n.GetBoolValue(); } },
                { "LastName", n => { LastName = n.GetStringValue(); } },
                { "mailTip", n => { MailTip = n.GetStringValue(); } },
                { "mobilePhone", n => { MobilePhone = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "PostalCode", n => { PostalCode = n.GetStringValue(); } },
                { "State", n => { State = n.GetStringValue(); } },
                { "StreetAddress", n => { StreetAddress = n.GetStringValue(); } },
                { "tenantID", n => { TenantID = n.GetStringValue(); } },
                { "Title", n => { Title = n.GetStringValue(); } },
                { "website", n => { Website = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("City", City);
            writer.WriteStringValue("Company", Company);
            writer.WriteStringValue("ContactID", ContactID);
            writer.WriteStringValue("CountryOrRegion", CountryOrRegion);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteBoolValue("hidefromGAL", HidefromGAL);
            writer.WriteStringValue("LastName", LastName);
            writer.WriteStringValue("mailTip", MailTip);
            writer.WriteStringValue("mobilePhone", MobilePhone);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("PostalCode", PostalCode);
            writer.WriteStringValue("State", State);
            writer.WriteStringValue("StreetAddress", StreetAddress);
            writer.WriteStringValue("tenantID", TenantID);
            writer.WriteStringValue("Title", Title);
            writer.WriteStringValue("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
