// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ListGraphRequest
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListGraphRequestGetRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? BlockType { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue BlockType { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? DbCacheType { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue DbCacheType { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? DbFormat { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue DbFormat { get; set; }
#endif
        /// <summary>The includeRawAttachments property</summary>
        public bool? IncludeRawAttachments { get; set; }
        /// <summary>The ooo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo? Ooo { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo Ooo { get; set; }
#endif
        /// <summary>The postExecution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? PostExecution { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> PostExecution { get; set; }
#endif
        /// <summary>The recipientLimits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_recipientLimits? RecipientLimits { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_recipientLimits RecipientLimits { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Recurrence { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Recurrence { get; set; }
#endif
        /// <summary>The removeRemediation property</summary>
        public bool? RemoveRemediation { get; set; }
        /// <summary>The scheduleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduleName { get; set; }
#nullable restore
#else
        public string ScheduleName { get; set; }
#endif
        /// <summary>The selectedTest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? SelectedTest { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> SelectedTest { get; set; }
#endif
        /// <summary>The templateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? TestSuite { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue TestSuite { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody"/> and sets the default values.
        /// </summary>
        public ListGraphRequestGetRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockType", n => { BlockType = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "dbCacheType", n => { DbCacheType = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "dbFormat", n => { DbFormat = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "includeRawAttachments", n => { IncludeRawAttachments = n.GetBoolValue(); } },
                { "ooo", n => { Ooo = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo>(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo.CreateFromDiscriminatorValue); } },
                { "postExecution", n => { PostExecution = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recipientLimits", n => { RecipientLimits = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_recipientLimits>(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_recipientLimits.CreateFromDiscriminatorValue); } },
                { "recurrence", n => { Recurrence = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "removeRemediation", n => { RemoveRemediation = n.GetBoolValue(); } },
                { "scheduleName", n => { ScheduleName = n.GetStringValue(); } },
                { "selectedTest", n => { SelectedTest = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "templateName", n => { TemplateName = n.GetStringValue(); } },
                { "testSuite", n => { TestSuite = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("blockType", BlockType);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("dbCacheType", DbCacheType);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("dbFormat", DbFormat);
            writer.WriteBoolValue("includeRawAttachments", IncludeRawAttachments);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo>("ooo", Ooo);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("postExecution", PostExecution);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_recipientLimits>("recipientLimits", RecipientLimits);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("recurrence", Recurrence);
            writer.WriteBoolValue("removeRemediation", RemoveRemediation);
            writer.WriteStringValue("scheduleName", ScheduleName);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("selectedTest", SelectedTest);
            writer.WriteStringValue("templateName", TemplateName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("testSuite", TestSuite);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
