// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.CIPP.Client.Api.ListGraphRequest
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ListGraphRequest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListGraphRequestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListGraphRequestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ListGraphRequest?tenantFilter={tenantFilter}{&AsApp*,CountOnly*,Endpoint*,IgnoreErrors*,ListProperties*,NoPagination*,QueueId*,QueueNameOverride*,ReverseTenantLookup*,ReverseTenantLookupProperty*,SkipCache*,Sort*,Version*,expand*,graphFilter*,manualPagination*,nextLink*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListGraphRequestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ListGraphRequest?tenantFilter={tenantFilter}{&AsApp*,CountOnly*,Endpoint*,IgnoreErrors*,ListProperties*,NoPagination*,QueueId*,QueueNameOverride*,ReverseTenantLookup*,ReverseTenantLookupProperty*,SkipCache*,Sort*,Version*,expand*,graphFilter*,manualPagination*,nextLink*}", rawUrl)
        {
        }
        /// <summary>
        /// ListGraphRequest
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Models.StandardResults"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults?> GetAsync(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder.ListGraphRequestRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults> GetAsync(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder.ListGraphRequestRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToGetRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.CIPP.Client.Models.StandardResults>(requestInfo, global::Bezalu.CIPP.Client.Models.StandardResults.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListGraphRequest
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder.ListGraphRequestRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody body, Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder.ListGraphRequestRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListGraphRequest
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListGraphRequestRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? AsApp { get; set; }
#nullable restore
#else
            public string AsApp { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? CountOnly { get; set; }
#nullable restore
#else
            public string CountOnly { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Endpoint { get; set; }
#nullable restore
#else
            public string Endpoint { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string Expand { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("graphFilter")]
            public string? GraphFilter { get; set; }
#nullable restore
#else
            [QueryParameter("graphFilter")]
            public string GraphFilter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? IgnoreErrors { get; set; }
#nullable restore
#else
            public string IgnoreErrors { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? ListProperties { get; set; }
#nullable restore
#else
            public string ListProperties { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("manualPagination")]
            public string? ManualPagination { get; set; }
#nullable restore
#else
            [QueryParameter("manualPagination")]
            public string ManualPagination { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nextLink")]
            public string? NextLink { get; set; }
#nullable restore
#else
            [QueryParameter("nextLink")]
            public string NextLink { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? NoPagination { get; set; }
#nullable restore
#else
            public string NoPagination { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? QueueId { get; set; }
#nullable restore
#else
            public string QueueId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? QueueNameOverride { get; set; }
#nullable restore
#else
            public string QueueNameOverride { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? ReverseTenantLookup { get; set; }
#nullable restore
#else
            public string ReverseTenantLookup { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? ReverseTenantLookupProperty { get; set; }
#nullable restore
#else
            public string ReverseTenantLookupProperty { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? SkipCache { get; set; }
#nullable restore
#else
            public string SkipCache { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Sort { get; set; }
#nullable restore
#else
            public string Sort { get; set; }
#endif
            /// <summary>Target tenant domain or &apos;AllTenants&apos; for multi-tenant operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tenantFilter")]
            public string? TenantFilter { get; set; }
#nullable restore
#else
            [QueryParameter("tenantFilter")]
            public string TenantFilter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Version { get; set; }
#nullable restore
#else
            public string Version { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListGraphRequestRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestRequestBuilder.ListGraphRequestRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
