// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ListGraphRequest
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListGraphRequestGetRequestBody_ooo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AutoDeclineFutureRequestsWhenOOF property</summary>
        public bool? AutoDeclineFutureRequestsWhenOOF { get; set; }
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? AutoReplyState { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue AutoReplyState { get; set; }
#endif
        /// <summary>The CreateOOFEvent property</summary>
        public bool? CreateOOFEvent { get; set; }
        /// <summary>The DeclineEventsForScheduledOOF property</summary>
        public bool? DeclineEventsForScheduledOOF { get; set; }
        /// <summary>The DeclineMeetingMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeclineMeetingMessage { get; set; }
#nullable restore
#else
        public string DeclineMeetingMessage { get; set; }
#endif
        /// <summary>The EndTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The ExternalMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalMessage { get; set; }
#nullable restore
#else
        public string ExternalMessage { get; set; }
#endif
        /// <summary>The InternalMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalMessage { get; set; }
#nullable restore
#else
        public string InternalMessage { get; set; }
#endif
        /// <summary>The OOFEventSubject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OOFEventSubject { get; set; }
#nullable restore
#else
        public string OOFEventSubject { get; set; }
#endif
        /// <summary>The StartTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo"/> and sets the default values.
        /// </summary>
        public ListGraphRequestGetRequestBody_ooo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ListGraphRequest.ListGraphRequestGetRequestBody_ooo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AutoDeclineFutureRequestsWhenOOF", n => { AutoDeclineFutureRequestsWhenOOF = n.GetBoolValue(); } },
                { "AutoReplyState", n => { AutoReplyState = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "CreateOOFEvent", n => { CreateOOFEvent = n.GetBoolValue(); } },
                { "DeclineEventsForScheduledOOF", n => { DeclineEventsForScheduledOOF = n.GetBoolValue(); } },
                { "DeclineMeetingMessage", n => { DeclineMeetingMessage = n.GetStringValue(); } },
                { "EndTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "ExternalMessage", n => { ExternalMessage = n.GetStringValue(); } },
                { "InternalMessage", n => { InternalMessage = n.GetStringValue(); } },
                { "OOFEventSubject", n => { OOFEventSubject = n.GetStringValue(); } },
                { "StartTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AutoDeclineFutureRequestsWhenOOF", AutoDeclineFutureRequestsWhenOOF);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("AutoReplyState", AutoReplyState);
            writer.WriteBoolValue("CreateOOFEvent", CreateOOFEvent);
            writer.WriteBoolValue("DeclineEventsForScheduledOOF", DeclineEventsForScheduledOOF);
            writer.WriteStringValue("DeclineMeetingMessage", DeclineMeetingMessage);
            writer.WriteDateTimeOffsetValue("EndTime", EndTime);
            writer.WriteStringValue("ExternalMessage", ExternalMessage);
            writer.WriteStringValue("InternalMessage", InternalMessage);
            writer.WriteStringValue("OOFEventSubject", OOFEventSubject);
            writer.WriteDateTimeOffsetValue("StartTime", StartTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
