// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddScriptedAlert
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddScriptedAlertPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Actions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? Actions { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AlertComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlertComment { get; set; }
#nullable restore
#else
        public string AlertComment { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Command { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Command { get; set; }
#endif
        /// <summary>The CustomSubject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomSubject { get; set; }
#nullable restore
#else
        public string CustomSubject { get; set; }
#endif
        /// <summary>The excludedTenants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExcludedTenants { get; set; }
#nullable restore
#else
        public string ExcludedTenants { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Logbook { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Logbook { get; set; }
#endif
        /// <summary>The postExecution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? PostExecution { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> PostExecution { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Preset { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Preset { get; set; }
#endif
        /// <summary>The PSObject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PSObject { get; set; }
#nullable restore
#else
        public string PSObject { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Recurrence { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Recurrence { get; set; }
#endif
        /// <summary>The RowKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RowKey { get; set; }
#nullable restore
#else
        public string RowKey { get; set; }
#endif
        /// <summary>The startDateTime property</summary>
        public DateTimeOffset? StartDateTime { get; set; }
        /// <summary>The tenantFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddScriptedAlert.AddScriptedAlertPostRequestBody"/> and sets the default values.
        /// </summary>
        public AddScriptedAlertPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddScriptedAlert.AddScriptedAlertPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddScriptedAlert.AddScriptedAlertPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddScriptedAlert.AddScriptedAlertPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Actions", n => { Actions = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "AlertComment", n => { AlertComment = n.GetStringValue(); } },
                { "command", n => { Command = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "CustomSubject", n => { CustomSubject = n.GetStringValue(); } },
                { "excludedTenants", n => { ExcludedTenants = n.GetStringValue(); } },
                { "logbook", n => { Logbook = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "PSObject", n => { PSObject = n.GetStringValue(); } },
                { "postExecution", n => { PostExecution = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "preset", n => { Preset = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "recurrence", n => { Recurrence = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "RowKey", n => { RowKey = n.GetStringValue(); } },
                { "startDateTime", n => { StartDateTime = n.GetDateTimeOffsetValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("Actions", Actions);
            writer.WriteStringValue("AlertComment", AlertComment);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("command", Command);
            writer.WriteStringValue("CustomSubject", CustomSubject);
            writer.WriteStringValue("excludedTenants", ExcludedTenants);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("logbook", Logbook);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("postExecution", PostExecution);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("preset", Preset);
            writer.WriteStringValue("PSObject", PSObject);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("recurrence", Recurrence);
            writer.WriteStringValue("RowKey", RowKey);
            writer.WriteDateTimeOffsetValue("startDateTime", StartDateTime);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
