// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.EditSafeLinksPolicyTemplate
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EditSafeLinksPolicyTemplatePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AdminDisplayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdminDisplayName { get; set; }
#nullable restore
#else
        public string AdminDisplayName { get; set; }
#endif
        /// <summary>The AllowClickThrough property</summary>
        public bool? AllowClickThrough { get; set; }
        /// <summary>The Comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>The CustomNotificationText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomNotificationText { get; set; }
#nullable restore
#else
        public string CustomNotificationText { get; set; }
#endif
        /// <summary>The DeliverMessageAfterScan property</summary>
        public bool? DeliverMessageAfterScan { get; set; }
        /// <summary>The DisableUrlRewrite property</summary>
        public bool? DisableUrlRewrite { get; set; }
        /// <summary>The DoNotRewriteUrls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DoNotRewriteUrls { get; set; }
#nullable restore
#else
        public List<string> DoNotRewriteUrls { get; set; }
#endif
        /// <summary>The EnableForInternalSenders property</summary>
        public bool? EnableForInternalSenders { get; set; }
        /// <summary>The EnableOrganizationBranding property</summary>
        public bool? EnableOrganizationBranding { get; set; }
        /// <summary>The EnableSafeLinksForEmail property</summary>
        public bool? EnableSafeLinksForEmail { get; set; }
        /// <summary>The EnableSafeLinksForOffice property</summary>
        public bool? EnableSafeLinksForOffice { get; set; }
        /// <summary>The EnableSafeLinksForTeams property</summary>
        public bool? EnableSafeLinksForTeams { get; set; }
        /// <summary>The ExceptIfRecipientDomainIs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExceptIfRecipientDomainIs { get; set; }
#nullable restore
#else
        public List<string> ExceptIfRecipientDomainIs { get; set; }
#endif
        /// <summary>The ExceptIfSentTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExceptIfSentTo { get; set; }
#nullable restore
#else
        public List<string> ExceptIfSentTo { get; set; }
#endif
        /// <summary>The ExceptIfSentToMemberOf property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExceptIfSentToMemberOf { get; set; }
#nullable restore
#else
        public List<string> ExceptIfSentToMemberOf { get; set; }
#endif
        /// <summary>Template GUID. PS1 requires this to locate and update the template in Azure Table Storage.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ID { get; set; }
#nullable restore
#else
        public string ID { get; set; }
#endif
        /// <summary>The PolicyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyName { get; set; }
#nullable restore
#else
        public string PolicyName { get; set; }
#endif
        /// <summary>The Priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The RecipientDomainIs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RecipientDomainIs { get; set; }
#nullable restore
#else
        public List<string> RecipientDomainIs { get; set; }
#endif
        /// <summary>The RuleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleName { get; set; }
#nullable restore
#else
        public string RuleName { get; set; }
#endif
        /// <summary>The ScanUrls property</summary>
        public bool? ScanUrls { get; set; }
        /// <summary>The SentTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SentTo { get; set; }
#nullable restore
#else
        public List<string> SentTo { get; set; }
#endif
        /// <summary>The SentToMemberOf property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SentToMemberOf { get; set; }
#nullable restore
#else
        public List<string> SentToMemberOf { get; set; }
#endif
        /// <summary>Formatter sends ruleValues.State ? &apos;Enabled&apos; : &apos;Disabled&apos; (string, not boolean) for template mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The TemplateDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateDescription { get; set; }
#nullable restore
#else
        public string TemplateDescription { get; set; }
#endif
        /// <summary>The TemplateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>Not consumed by PS1 (AnyTenant endpoint) but included by formatter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>The TrackClicks property</summary>
        public bool? TrackClicks { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.EditSafeLinksPolicyTemplate.EditSafeLinksPolicyTemplatePostRequestBody"/> and sets the default values.
        /// </summary>
        public EditSafeLinksPolicyTemplatePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.EditSafeLinksPolicyTemplate.EditSafeLinksPolicyTemplatePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.EditSafeLinksPolicyTemplate.EditSafeLinksPolicyTemplatePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.EditSafeLinksPolicyTemplate.EditSafeLinksPolicyTemplatePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AdminDisplayName", n => { AdminDisplayName = n.GetStringValue(); } },
                { "AllowClickThrough", n => { AllowClickThrough = n.GetBoolValue(); } },
                { "Comments", n => { Comments = n.GetStringValue(); } },
                { "CustomNotificationText", n => { CustomNotificationText = n.GetStringValue(); } },
                { "DeliverMessageAfterScan", n => { DeliverMessageAfterScan = n.GetBoolValue(); } },
                { "DisableUrlRewrite", n => { DisableUrlRewrite = n.GetBoolValue(); } },
                { "DoNotRewriteUrls", n => { DoNotRewriteUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "EnableForInternalSenders", n => { EnableForInternalSenders = n.GetBoolValue(); } },
                { "EnableOrganizationBranding", n => { EnableOrganizationBranding = n.GetBoolValue(); } },
                { "EnableSafeLinksForEmail", n => { EnableSafeLinksForEmail = n.GetBoolValue(); } },
                { "EnableSafeLinksForOffice", n => { EnableSafeLinksForOffice = n.GetBoolValue(); } },
                { "EnableSafeLinksForTeams", n => { EnableSafeLinksForTeams = n.GetBoolValue(); } },
                { "ExceptIfRecipientDomainIs", n => { ExceptIfRecipientDomainIs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ExceptIfSentTo", n => { ExceptIfSentTo = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ExceptIfSentToMemberOf", n => { ExceptIfSentToMemberOf = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ID", n => { ID = n.GetStringValue(); } },
                { "PolicyName", n => { PolicyName = n.GetStringValue(); } },
                { "Priority", n => { Priority = n.GetIntValue(); } },
                { "RecipientDomainIs", n => { RecipientDomainIs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "RuleName", n => { RuleName = n.GetStringValue(); } },
                { "ScanUrls", n => { ScanUrls = n.GetBoolValue(); } },
                { "SentTo", n => { SentTo = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "SentToMemberOf", n => { SentToMemberOf = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "State", n => { State = n.GetStringValue(); } },
                { "TemplateDescription", n => { TemplateDescription = n.GetStringValue(); } },
                { "TemplateName", n => { TemplateName = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "TrackClicks", n => { TrackClicks = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AdminDisplayName", AdminDisplayName);
            writer.WriteBoolValue("AllowClickThrough", AllowClickThrough);
            writer.WriteStringValue("Comments", Comments);
            writer.WriteStringValue("CustomNotificationText", CustomNotificationText);
            writer.WriteBoolValue("DeliverMessageAfterScan", DeliverMessageAfterScan);
            writer.WriteBoolValue("DisableUrlRewrite", DisableUrlRewrite);
            writer.WriteCollectionOfPrimitiveValues<string>("DoNotRewriteUrls", DoNotRewriteUrls);
            writer.WriteBoolValue("EnableForInternalSenders", EnableForInternalSenders);
            writer.WriteBoolValue("EnableOrganizationBranding", EnableOrganizationBranding);
            writer.WriteBoolValue("EnableSafeLinksForEmail", EnableSafeLinksForEmail);
            writer.WriteBoolValue("EnableSafeLinksForOffice", EnableSafeLinksForOffice);
            writer.WriteBoolValue("EnableSafeLinksForTeams", EnableSafeLinksForTeams);
            writer.WriteCollectionOfPrimitiveValues<string>("ExceptIfRecipientDomainIs", ExceptIfRecipientDomainIs);
            writer.WriteCollectionOfPrimitiveValues<string>("ExceptIfSentTo", ExceptIfSentTo);
            writer.WriteCollectionOfPrimitiveValues<string>("ExceptIfSentToMemberOf", ExceptIfSentToMemberOf);
            writer.WriteStringValue("ID", ID);
            writer.WriteStringValue("PolicyName", PolicyName);
            writer.WriteIntValue("Priority", Priority);
            writer.WriteCollectionOfPrimitiveValues<string>("RecipientDomainIs", RecipientDomainIs);
            writer.WriteStringValue("RuleName", RuleName);
            writer.WriteBoolValue("ScanUrls", ScanUrls);
            writer.WriteCollectionOfPrimitiveValues<string>("SentTo", SentTo);
            writer.WriteCollectionOfPrimitiveValues<string>("SentToMemberOf", SentToMemberOf);
            writer.WriteStringValue("State", State);
            writer.WriteStringValue("TemplateDescription", TemplateDescription);
            writer.WriteStringValue("TemplateName", TemplateName);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteBoolValue("TrackClicks", TrackClicks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
