// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddWin32ScriptApp
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddWin32ScriptAppPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Body parameter from PS1: applicationName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationName { get; set; }
#nullable restore
#else
        public string ApplicationName { get; set; }
#endif
        /// <summary>AssignTo parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignTo { get; set; }
#nullable restore
#else
        public string AssignTo { get; set; }
#endif
        /// <summary>CustomGroup parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomGroup { get; set; }
#nullable restore
#else
        public string CustomGroup { get; set; }
#endif
        /// <summary>description parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>detectionFile parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionFile { get; set; }
#nullable restore
#else
        public string DetectionFile { get; set; }
#endif
        /// <summary>detectionPath parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionPath { get; set; }
#nullable restore
#else
        public string DetectionPath { get; set; }
#endif
        /// <summary>The detectionScript property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionScript { get; set; }
#nullable restore
#else
        public string DetectionScript { get; set; }
#endif
        /// <summary>DisableRestart parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisableRestart { get; set; }
#nullable restore
#else
        public string DisableRestart { get; set; }
#endif
        /// <summary>enforceSignatureCheck parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnforceSignatureCheck { get; set; }
#nullable restore
#else
        public string EnforceSignatureCheck { get; set; }
#endif
        /// <summary>InstallAsSystem parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallAsSystem { get; set; }
#nullable restore
#else
        public string InstallAsSystem { get; set; }
#endif
        /// <summary>InstallationIntent parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallationIntent { get; set; }
#nullable restore
#else
        public string InstallationIntent { get; set; }
#endif
        /// <summary>installScript parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallScript { get; set; }
#nullable restore
#else
        public string InstallScript { get; set; }
#endif
        /// <summary>publisher parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Publisher { get; set; }
#nullable restore
#else
        public string Publisher { get; set; }
#endif
        /// <summary>runAs32Bit parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunAs32Bit { get; set; }
#nullable restore
#else
        public string RunAs32Bit { get; set; }
#endif
        /// <summary>selectedTenants parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelectedTenants { get; set; }
#nullable restore
#else
        public string SelectedTenants { get; set; }
#endif
        /// <summary>uninstallScript parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UninstallScript { get; set; }
#nullable restore
#else
        public string UninstallScript { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddWin32ScriptApp.AddWin32ScriptAppPostRequestBody"/> and sets the default values.
        /// </summary>
        public AddWin32ScriptAppPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddWin32ScriptApp.AddWin32ScriptAppPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddWin32ScriptApp.AddWin32ScriptAppPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddWin32ScriptApp.AddWin32ScriptAppPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applicationName", n => { ApplicationName = n.GetStringValue(); } },
                { "AssignTo", n => { AssignTo = n.GetStringValue(); } },
                { "CustomGroup", n => { CustomGroup = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "detectionFile", n => { DetectionFile = n.GetStringValue(); } },
                { "detectionPath", n => { DetectionPath = n.GetStringValue(); } },
                { "detectionScript", n => { DetectionScript = n.GetStringValue(); } },
                { "DisableRestart", n => { DisableRestart = n.GetStringValue(); } },
                { "enforceSignatureCheck", n => { EnforceSignatureCheck = n.GetStringValue(); } },
                { "InstallAsSystem", n => { InstallAsSystem = n.GetStringValue(); } },
                { "installScript", n => { InstallScript = n.GetStringValue(); } },
                { "InstallationIntent", n => { InstallationIntent = n.GetStringValue(); } },
                { "publisher", n => { Publisher = n.GetStringValue(); } },
                { "runAs32Bit", n => { RunAs32Bit = n.GetStringValue(); } },
                { "selectedTenants", n => { SelectedTenants = n.GetStringValue(); } },
                { "uninstallScript", n => { UninstallScript = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("applicationName", ApplicationName);
            writer.WriteStringValue("AssignTo", AssignTo);
            writer.WriteStringValue("CustomGroup", CustomGroup);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("detectionFile", DetectionFile);
            writer.WriteStringValue("detectionPath", DetectionPath);
            writer.WriteStringValue("detectionScript", DetectionScript);
            writer.WriteStringValue("DisableRestart", DisableRestart);
            writer.WriteStringValue("enforceSignatureCheck", EnforceSignatureCheck);
            writer.WriteStringValue("InstallAsSystem", InstallAsSystem);
            writer.WriteStringValue("InstallationIntent", InstallationIntent);
            writer.WriteStringValue("installScript", InstallScript);
            writer.WriteStringValue("publisher", Publisher);
            writer.WriteStringValue("runAs32Bit", RunAs32Bit);
            writer.WriteStringValue("selectedTenants", SelectedTenants);
            writer.WriteStringValue("uninstallScript", UninstallScript);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
