// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecNotificationConfig
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecNotificationConfigPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? LogsToInclude { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue LogsToInclude { get; set; }
#endif
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
        public bool? OnePerTenant { get; set; }
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
        public bool? SendtoIntegration { get; set; }
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Severity { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Severity { get; set; }
#endif
        /// <summary>The UseStandardizedSchema property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseStandardizedSchema { get; set; }
#nullable restore
#else
        public string UseStandardizedSchema { get; set; }
#endif
        /// <summary>(auto) from CippNotificationForm.jsx</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Webhook { get; set; }
#nullable restore
#else
        public string Webhook { get; set; }
#endif
        /// <summary>The webhookAuthHeaderName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthHeaderName { get; set; }
#nullable restore
#else
        public string WebhookAuthHeaderName { get; set; }
#endif
        /// <summary>The webhookAuthHeaders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthHeaders { get; set; }
#nullable restore
#else
        public string WebhookAuthHeaders { get; set; }
#endif
        /// <summary>The webhookAuthHeaderValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthHeaderValue { get; set; }
#nullable restore
#else
        public string WebhookAuthHeaderValue { get; set; }
#endif
        /// <summary>The webhookAuthPassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthPassword { get; set; }
#nullable restore
#else
        public string WebhookAuthPassword { get; set; }
#endif
        /// <summary>The webhookAuthToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthToken { get; set; }
#nullable restore
#else
        public string WebhookAuthToken { get; set; }
#endif
        /// <summary>The webhookAuthType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthType { get; set; }
#nullable restore
#else
        public string WebhookAuthType { get; set; }
#endif
        /// <summary>The webhookAuthUsername property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookAuthUsername { get; set; }
#nullable restore
#else
        public string WebhookAuthUsername { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecNotificationConfig.ExecNotificationConfigPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExecNotificationConfigPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecNotificationConfig.ExecNotificationConfigPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecNotificationConfig.ExecNotificationConfigPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecNotificationConfig.ExecNotificationConfigPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "logsToInclude", n => { LogsToInclude = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "onePerTenant", n => { OnePerTenant = n.GetBoolValue(); } },
                { "sendtoIntegration", n => { SendtoIntegration = n.GetBoolValue(); } },
                { "Severity", n => { Severity = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "UseStandardizedSchema", n => { UseStandardizedSchema = n.GetStringValue(); } },
                { "webhook", n => { Webhook = n.GetStringValue(); } },
                { "webhookAuthHeaderName", n => { WebhookAuthHeaderName = n.GetStringValue(); } },
                { "webhookAuthHeaderValue", n => { WebhookAuthHeaderValue = n.GetStringValue(); } },
                { "webhookAuthHeaders", n => { WebhookAuthHeaders = n.GetStringValue(); } },
                { "webhookAuthPassword", n => { WebhookAuthPassword = n.GetStringValue(); } },
                { "webhookAuthToken", n => { WebhookAuthToken = n.GetStringValue(); } },
                { "webhookAuthType", n => { WebhookAuthType = n.GetStringValue(); } },
                { "webhookAuthUsername", n => { WebhookAuthUsername = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("logsToInclude", LogsToInclude);
            writer.WriteBoolValue("onePerTenant", OnePerTenant);
            writer.WriteBoolValue("sendtoIntegration", SendtoIntegration);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("Severity", Severity);
            writer.WriteStringValue("UseStandardizedSchema", UseStandardizedSchema);
            writer.WriteStringValue("webhook", Webhook);
            writer.WriteStringValue("webhookAuthHeaderName", WebhookAuthHeaderName);
            writer.WriteStringValue("webhookAuthHeaders", WebhookAuthHeaders);
            writer.WriteStringValue("webhookAuthHeaderValue", WebhookAuthHeaderValue);
            writer.WriteStringValue("webhookAuthPassword", WebhookAuthPassword);
            writer.WriteStringValue("webhookAuthToken", WebhookAuthToken);
            writer.WriteStringValue("webhookAuthType", WebhookAuthType);
            writer.WriteStringValue("webhookAuthUsername", WebhookAuthUsername);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
