// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecScheduleOOOVacation
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecScheduleOOOVacationPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AutoDeclineFutureRequestsWhenOOF property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoDeclineFutureRequestsWhenOOF { get; set; }
#nullable restore
#else
        public string AutoDeclineFutureRequestsWhenOOF { get; set; }
#endif
        /// <summary>The CreateOOFEvent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateOOFEvent { get; set; }
#nullable restore
#else
        public string CreateOOFEvent { get; set; }
#endif
        /// <summary>The DeclineEventsForScheduledOOF property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeclineEventsForScheduledOOF { get; set; }
#nullable restore
#else
        public string DeclineEventsForScheduledOOF { get; set; }
#endif
        /// <summary>The DeclineMeetingMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeclineMeetingMessage { get; set; }
#nullable restore
#else
        public string DeclineMeetingMessage { get; set; }
#endif
        /// <summary>The endDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>The externalMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalMessage { get; set; }
#nullable restore
#else
        public string ExternalMessage { get; set; }
#endif
        /// <summary>The internalMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalMessage { get; set; }
#nullable restore
#else
        public string InternalMessage { get; set; }
#endif
        /// <summary>The OOFEventSubject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OOFEventSubject { get; set; }
#nullable restore
#else
        public string OOFEventSubject { get; set; }
#endif
        /// <summary>Notification channels triggered after task completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.PostExecution? PostExecution { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.PostExecution PostExecution { get; set; }
#endif
        /// <summary>The reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>The startDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The tenantFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>The Users property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Users { get; set; }
#nullable restore
#else
        public string Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecScheduleOOOVacation.ExecScheduleOOOVacationPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExecScheduleOOOVacationPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecScheduleOOOVacation.ExecScheduleOOOVacationPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecScheduleOOOVacation.ExecScheduleOOOVacationPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecScheduleOOOVacation.ExecScheduleOOOVacationPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AutoDeclineFutureRequestsWhenOOF", n => { AutoDeclineFutureRequestsWhenOOF = n.GetStringValue(); } },
                { "CreateOOFEvent", n => { CreateOOFEvent = n.GetStringValue(); } },
                { "DeclineEventsForScheduledOOF", n => { DeclineEventsForScheduledOOF = n.GetStringValue(); } },
                { "DeclineMeetingMessage", n => { DeclineMeetingMessage = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetStringValue(); } },
                { "externalMessage", n => { ExternalMessage = n.GetStringValue(); } },
                { "internalMessage", n => { InternalMessage = n.GetStringValue(); } },
                { "OOFEventSubject", n => { OOFEventSubject = n.GetStringValue(); } },
                { "postExecution", n => { PostExecution = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.PostExecution>(global::Bezalu.CIPP.Client.Models.PostExecution.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "Users", n => { Users = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AutoDeclineFutureRequestsWhenOOF", AutoDeclineFutureRequestsWhenOOF);
            writer.WriteStringValue("CreateOOFEvent", CreateOOFEvent);
            writer.WriteStringValue("DeclineEventsForScheduledOOF", DeclineEventsForScheduledOOF);
            writer.WriteStringValue("DeclineMeetingMessage", DeclineMeetingMessage);
            writer.WriteStringValue("endDate", EndDate);
            writer.WriteStringValue("externalMessage", ExternalMessage);
            writer.WriteStringValue("internalMessage", InternalMessage);
            writer.WriteStringValue("OOFEventSubject", OOFEventSubject);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.PostExecution>("postExecution", PostExecution);
            writer.WriteStringValue("reference", Reference);
            writer.WriteStringValue("startDate", StartDate);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("Users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
