// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddQuarantinePolicy
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddQuarantinePolicyPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AllowSender parameter</summary>
        public bool? AllowSender { get; set; }
        /// <summary>BlockSender parameter</summary>
        public bool? BlockSender { get; set; }
        /// <summary>Delete parameter</summary>
        public bool? Delete { get; set; }
        /// <summary>IncludeMessagesFromBlockedSenderAddress parameter</summary>
        public bool? IncludeMessagesFromBlockedSenderAddress { get; set; }
        /// <summary>Name parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Preview parameter</summary>
        public bool? Preview { get; set; }
        /// <summary>QuarantineNotification parameter</summary>
        public bool? QuarantineNotification { get; set; }
        /// <summary>ReleaseActionPreference parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ReleaseActionPreference { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ReleaseActionPreference { get; set; }
#endif
        /// <summary>selectedTenants parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelectedTenants { get; set; }
#nullable restore
#else
        public string SelectedTenants { get; set; }
#endif
        /// <summary>TemplateList parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? TemplateList { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue TemplateList { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddQuarantinePolicy.AddQuarantinePolicyPostRequestBody"/> and sets the default values.
        /// </summary>
        public AddQuarantinePolicyPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddQuarantinePolicy.AddQuarantinePolicyPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddQuarantinePolicy.AddQuarantinePolicyPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddQuarantinePolicy.AddQuarantinePolicyPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AllowSender", n => { AllowSender = n.GetBoolValue(); } },
                { "BlockSender", n => { BlockSender = n.GetBoolValue(); } },
                { "Delete", n => { Delete = n.GetBoolValue(); } },
                { "IncludeMessagesFromBlockedSenderAddress", n => { IncludeMessagesFromBlockedSenderAddress = n.GetBoolValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "Preview", n => { Preview = n.GetBoolValue(); } },
                { "QuarantineNotification", n => { QuarantineNotification = n.GetBoolValue(); } },
                { "ReleaseActionPreference", n => { ReleaseActionPreference = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "selectedTenants", n => { SelectedTenants = n.GetStringValue(); } },
                { "TemplateList", n => { TemplateList = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AllowSender", AllowSender);
            writer.WriteBoolValue("BlockSender", BlockSender);
            writer.WriteBoolValue("Delete", Delete);
            writer.WriteBoolValue("IncludeMessagesFromBlockedSenderAddress", IncludeMessagesFromBlockedSenderAddress);
            writer.WriteStringValue("Name", Name);
            writer.WriteBoolValue("Preview", Preview);
            writer.WriteBoolValue("QuarantineNotification", QuarantineNotification);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("ReleaseActionPreference", ReleaseActionPreference);
            writer.WriteStringValue("selectedTenants", SelectedTenants);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("TemplateList", TemplateList);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
