// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecCommunityRepo
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecCommunityRepoDeleteRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Action parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Branch parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>Description parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>FullName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>GUID parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GUID { get; set; }
#nullable restore
#else
        public string GUID { get; set; }
#endif
        /// <summary>Id parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>includeforks parameter</summary>
        public bool? Includeforks { get; set; }
        /// <summary>Message parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>orgName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? OrgName { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue OrgName { get; set; }
#endif
        /// <summary>Path parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>policySource parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? PolicySource { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue PolicySource { get; set; }
#endif
        /// <summary>Private parameter</summary>
        public bool? Private { get; set; }
        /// <summary>repoName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepoName { get; set; }
#nullable restore
#else
        public string RepoName { get; set; }
#endif
        /// <summary>searchTerm parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SearchTerm { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SearchTerm { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecCommunityRepo.ExecCommunityRepoDeleteRequestBody"/> and sets the default values.
        /// </summary>
        public ExecCommunityRepoDeleteRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecCommunityRepo.ExecCommunityRepoDeleteRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecCommunityRepo.ExecCommunityRepoDeleteRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecCommunityRepo.ExecCommunityRepoDeleteRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Action", n => { Action = n.GetStringValue(); } },
                { "Branch", n => { Branch = n.GetStringValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "FullName", n => { FullName = n.GetStringValue(); } },
                { "GUID", n => { GUID = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetStringValue(); } },
                { "includeforks", n => { Includeforks = n.GetBoolValue(); } },
                { "Message", n => { Message = n.GetStringValue(); } },
                { "orgName", n => { OrgName = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "Path", n => { Path = n.GetStringValue(); } },
                { "policySource", n => { PolicySource = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "Private", n => { Private = n.GetBoolValue(); } },
                { "repoName", n => { RepoName = n.GetStringValue(); } },
                { "searchTerm", n => { SearchTerm = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("Action", Action);
            writer.WriteStringValue("Branch", Branch);
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("FullName", FullName);
            writer.WriteStringValue("GUID", GUID);
            writer.WriteStringValue("Id", Id);
            writer.WriteBoolValue("includeforks", Includeforks);
            writer.WriteStringValue("Message", Message);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("orgName", OrgName);
            writer.WriteStringValue("Path", Path);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("policySource", PolicySource);
            writer.WriteBoolValue("Private", Private);
            writer.WriteStringValue("repoName", RepoName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("searchTerm", SearchTerm);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
