// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddOfficeApp
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddOfficeAppPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AcceptLicense property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcceptLicense { get; set; }
#nullable restore
#else
        public string AcceptLicense { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The arch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arch { get; set; }
#nullable restore
#else
        public string Arch { get; set; }
#endif
        /// <summary>The AssignTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignTo { get; set; }
#nullable restore
#else
        public string AssignTo { get; set; }
#endif
        /// <summary>The CustomGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomGroup { get; set; }
#nullable restore
#else
        public string CustomGroup { get; set; }
#endif
        /// <summary>The customXml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomXml { get; set; }
#nullable restore
#else
        public string CustomXml { get; set; }
#endif
        /// <summary>The excludedApps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExcludedApps { get; set; }
#nullable restore
#else
        public string ExcludedApps { get; set; }
#endif
        /// <summary>The IntuneBody property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntuneBody { get; set; }
#nullable restore
#else
        public string IntuneBody { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Languages { get; set; }
#nullable restore
#else
        public string Languages { get; set; }
#endif
        /// <summary>The RemoveVersions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveVersions { get; set; }
#nullable restore
#else
        public string RemoveVersions { get; set; }
#endif
        /// <summary>The selectedTenants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelectedTenants { get; set; }
#nullable restore
#else
        public string SelectedTenants { get; set; }
#endif
        /// <summary>The SharedComputerActivation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SharedComputerActivation { get; set; }
#nullable restore
#else
        public string SharedComputerActivation { get; set; }
#endif
        /// <summary>The updateChannel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateChannel { get; set; }
#nullable restore
#else
        public string UpdateChannel { get; set; }
#endif
        /// <summary>The useCustomXml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseCustomXml { get; set; }
#nullable restore
#else
        public string UseCustomXml { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddOfficeApp.AddOfficeAppPostRequestBody"/> and sets the default values.
        /// </summary>
        public AddOfficeAppPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddOfficeApp.AddOfficeAppPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddOfficeApp.AddOfficeAppPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddOfficeApp.AddOfficeAppPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AcceptLicense", n => { AcceptLicense = n.GetStringValue(); } },
                { "arch", n => { Arch = n.GetStringValue(); } },
                { "AssignTo", n => { AssignTo = n.GetStringValue(); } },
                { "CustomGroup", n => { CustomGroup = n.GetStringValue(); } },
                { "customXml", n => { CustomXml = n.GetStringValue(); } },
                { "excludedApps", n => { ExcludedApps = n.GetStringValue(); } },
                { "IntuneBody", n => { IntuneBody = n.GetStringValue(); } },
                { "languages", n => { Languages = n.GetStringValue(); } },
                { "RemoveVersions", n => { RemoveVersions = n.GetStringValue(); } },
                { "selectedTenants", n => { SelectedTenants = n.GetStringValue(); } },
                { "SharedComputerActivation", n => { SharedComputerActivation = n.GetStringValue(); } },
                { "updateChannel", n => { UpdateChannel = n.GetStringValue(); } },
                { "useCustomXml", n => { UseCustomXml = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AcceptLicense", AcceptLicense);
            writer.WriteStringValue("arch", Arch);
            writer.WriteStringValue("AssignTo", AssignTo);
            writer.WriteStringValue("CustomGroup", CustomGroup);
            writer.WriteStringValue("customXml", CustomXml);
            writer.WriteStringValue("excludedApps", ExcludedApps);
            writer.WriteStringValue("IntuneBody", IntuneBody);
            writer.WriteStringValue("languages", Languages);
            writer.WriteStringValue("RemoveVersions", RemoveVersions);
            writer.WriteStringValue("selectedTenants", SelectedTenants);
            writer.WriteStringValue("SharedComputerActivation", SharedComputerActivation);
            writer.WriteStringValue("updateChannel", UpdateChannel);
            writer.WriteStringValue("useCustomXml", UseCustomXml);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
