// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ListMessageTrace
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListMessageTracePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>dateFilter parameter</summary>
        public global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody_dateFilter? DateFilter { get; set; }
        /// <summary>days parameter</summary>
        public double? Days { get; set; }
        /// <summary>endDate parameter</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>fromIP parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromIP { get; set; }
#nullable restore
#else
        public string FromIP { get; set; }
#endif
        /// <summary>ID parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ID { get; set; }
#nullable restore
#else
        public string ID { get; set; }
#endif
        /// <summary>Body parameter from PS1: MessageId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageId { get; set; }
#nullable restore
#else
        public string MessageId { get; set; }
#endif
        /// <summary>recipient parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Recipient { get; set; }
#nullable restore
#else
        public List<string> Recipient { get; set; }
#endif
        /// <summary>sender parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Sender { get; set; }
#nullable restore
#else
        public List<string> Sender { get; set; }
#endif
        /// <summary>startDate parameter</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>status parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Status { get; set; }
#nullable restore
#else
        public List<string> Status { get; set; }
#endif
        /// <summary>tenantFilter parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>toIP parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToIP { get; set; }
#nullable restore
#else
        public string ToIP { get; set; }
#endif
        /// <summary>traceDetail parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceDetail { get; set; }
#nullable restore
#else
        public string TraceDetail { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody"/> and sets the default values.
        /// </summary>
        public ListMessageTracePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dateFilter", n => { DateFilter = n.GetEnumValue<global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody_dateFilter>(); } },
                { "days", n => { Days = n.GetDoubleValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "fromIP", n => { FromIP = n.GetStringValue(); } },
                { "ID", n => { ID = n.GetStringValue(); } },
                { "MessageId", n => { MessageId = n.GetStringValue(); } },
                { "recipient", n => { Recipient = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sender", n => { Sender = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "toIP", n => { ToIP = n.GetStringValue(); } },
                { "traceDetail", n => { TraceDetail = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Bezalu.CIPP.Client.Api.ListMessageTrace.ListMessageTracePostRequestBody_dateFilter>("dateFilter", DateFilter);
            writer.WriteDoubleValue("days", Days);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteStringValue("fromIP", FromIP);
            writer.WriteStringValue("ID", ID);
            writer.WriteStringValue("MessageId", MessageId);
            writer.WriteCollectionOfPrimitiveValues<string>("recipient", Recipient);
            writer.WriteCollectionOfPrimitiveValues<string>("sender", Sender);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteCollectionOfPrimitiveValues<string>("status", Status);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("toIP", ToIP);
            writer.WriteStringValue("traceDetail", TraceDetail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
