// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.EditGroup
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EditGroupPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Array of contact objects to add [{value: email/guid, addedFields: {id, displayName, WindowsEmailAddress}}].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddContact { get; set; }
#nullable restore
#else
        public List<string> AddContact { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of user objects to add as members [{value: id, addedFields: {userPrincipalName, displayName, id}}].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddMember { get; set; }
#nullable restore
#else
        public List<string> AddMember { get; set; }
#endif
        /// <summary>Array of user objects to add as owners.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AddOwner { get; set; }
#nullable restore
#else
        public List<string> AddOwner { get; set; }
#endif
        /// <summary>Allow external senders. Only sent if changed.</summary>
        public bool? AllowExternal { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>New display name. PS1 reads as groupName ?? displayName ?? groupId.addedFields.groupName.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Group ID string. PS1 reads $UserObj.groupId.value ?? $UserObj.groupId.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody_groupId? GroupId { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody_groupId GroupId { get; set; }
#endif
        /// <summary>Body parameter from PS1: groupName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>Group type string e.g. &apos;Microsoft 365&apos;, &apos;Security&apos;, &apos;Distribution List&apos;, &apos;Mail-Enabled Security&apos;. PS1 reads $UserObj.groupId.addedFields.groupType ?? $UserObj.groupType.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupType { get; set; }
#nullable restore
#else
        public string GroupType { get; set; }
#endif
        /// <summary>Hide group from Outlook (M365 groups). Only sent if changed.</summary>
        public bool? HideFromOutlookClients { get; set; }
        /// <summary>Group email address; used for ExO DL operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mail { get; set; }
#nullable restore
#else
        public string Mail { get; set; }
#endif
        /// <summary>The mailNickname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailNickname { get; set; }
#nullable restore
#else
        public string MailNickname { get; set; }
#endif
        /// <summary>Dynamic membership rule expression. Only used for DynamicMembership groups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MembershipRules { get; set; }
#nullable restore
#else
        public string MembershipRules { get; set; }
#endif
        /// <summary>Array of contact objects to remove [{value: mail/guid, addedFields: {id}}].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveContact { get; set; }
#nullable restore
#else
        public List<string> RemoveContact { get; set; }
#endif
        /// <summary>Array of user objects to remove [{value: id, addedFields: {userPrincipalName}}].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveMember { get; set; }
#nullable restore
#else
        public List<string> RemoveMember { get; set; }
#endif
        /// <summary>Array of user objects to remove from owners.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RemoveOwner { get; set; }
#nullable restore
#else
        public List<string> RemoveOwner { get; set; }
#endif
        /// <summary>Only sent if changed from initial value (customDataformatter deletes unchanged properties).</summary>
        public bool? SecurityEnabled { get; set; }
        /// <summary>Send copies to member inboxes (M365 groups). Only sent if changed.</summary>
        public bool? SendCopies { get; set; }
        /// <summary>Tenant domain. PS1 reads $UserObj.tenantFilter and falls back to $UserObj.tenantId.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>Body parameter from PS1: tenantId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantId { get; set; }
#nullable restore
#else
        public string TenantId { get; set; }
#endif
        /// <summary>&apos;Public&apos;|&apos;Private&apos;. Only sent if changed from initial value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Visibility { get; set; }
#nullable restore
#else
        public string Visibility { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody"/> and sets the default values.
        /// </summary>
        public EditGroupPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddContact", n => { AddContact = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "AddMember", n => { AddMember = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "AddOwner", n => { AddOwner = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowExternal", n => { AllowExternal = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "groupId", n => { GroupId = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody_groupId>(global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody_groupId.CreateFromDiscriminatorValue); } },
                { "groupName", n => { GroupName = n.GetStringValue(); } },
                { "groupType", n => { GroupType = n.GetStringValue(); } },
                { "hideFromOutlookClients", n => { HideFromOutlookClients = n.GetBoolValue(); } },
                { "mail", n => { Mail = n.GetStringValue(); } },
                { "mailNickname", n => { MailNickname = n.GetStringValue(); } },
                { "membershipRules", n => { MembershipRules = n.GetStringValue(); } },
                { "RemoveContact", n => { RemoveContact = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "RemoveMember", n => { RemoveMember = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "RemoveOwner", n => { RemoveOwner = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "securityEnabled", n => { SecurityEnabled = n.GetBoolValue(); } },
                { "sendCopies", n => { SendCopies = n.GetBoolValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "tenantId", n => { TenantId = n.GetStringValue(); } },
                { "visibility", n => { Visibility = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("AddContact", AddContact);
            writer.WriteCollectionOfPrimitiveValues<string>("AddMember", AddMember);
            writer.WriteCollectionOfPrimitiveValues<string>("AddOwner", AddOwner);
            writer.WriteBoolValue("allowExternal", AllowExternal);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.EditGroup.EditGroupPatchRequestBody_groupId>("groupId", GroupId);
            writer.WriteStringValue("groupName", GroupName);
            writer.WriteStringValue("groupType", GroupType);
            writer.WriteBoolValue("hideFromOutlookClients", HideFromOutlookClients);
            writer.WriteStringValue("mail", Mail);
            writer.WriteStringValue("mailNickname", MailNickname);
            writer.WriteStringValue("membershipRules", MembershipRules);
            writer.WriteCollectionOfPrimitiveValues<string>("RemoveContact", RemoveContact);
            writer.WriteCollectionOfPrimitiveValues<string>("RemoveMember", RemoveMember);
            writer.WriteCollectionOfPrimitiveValues<string>("RemoveOwner", RemoveOwner);
            writer.WriteBoolValue("securityEnabled", SecurityEnabled);
            writer.WriteBoolValue("sendCopies", SendCopies);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("tenantId", TenantId);
            writer.WriteStringValue("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
