// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddSite
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddSitePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>sensitivityLabel parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SensitivityLabel { get; set; }
#nullable restore
#else
        public string SensitivityLabel { get; set; }
#endif
        /// <summary>siteDescription parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteDescription { get; set; }
#nullable restore
#else
        public string SiteDescription { get; set; }
#endif
        /// <summary>siteDesign parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteDesign? SiteDesign { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteDesign SiteDesign { get; set; }
#endif
        /// <summary>siteName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteName { get; set; }
#nullable restore
#else
        public string SiteName { get; set; }
#endif
        /// <summary>siteOwner parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteOwner? SiteOwner { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteOwner SiteOwner { get; set; }
#endif
        /// <summary>templateName parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_templateName? TemplateName { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_templateName TemplateName { get; set; }
#endif
        /// <summary>tenantFilter parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody"/> and sets the default values.
        /// </summary>
        public AddSitePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "sensitivityLabel", n => { SensitivityLabel = n.GetStringValue(); } },
                { "siteDescription", n => { SiteDescription = n.GetStringValue(); } },
                { "siteDesign", n => { SiteDesign = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteDesign>(global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteDesign.CreateFromDiscriminatorValue); } },
                { "siteName", n => { SiteName = n.GetStringValue(); } },
                { "siteOwner", n => { SiteOwner = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteOwner>(global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteOwner.CreateFromDiscriminatorValue); } },
                { "templateName", n => { TemplateName = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_templateName>(global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_templateName.CreateFromDiscriminatorValue); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("sensitivityLabel", SensitivityLabel);
            writer.WriteStringValue("siteDescription", SiteDescription);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteDesign>("siteDesign", SiteDesign);
            writer.WriteStringValue("siteName", SiteName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_siteOwner>("siteOwner", SiteOwner);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.AddSite.AddSitePostRequestBody_templateName>("templateName", TemplateName);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
