// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.AddUserDefaults
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddUserDefaultsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Additional SMTP aliases, newline-delimited (server splits on \n)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddedAliases { get; set; }
#nullable restore
#else
        public string AddedAliases { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addToGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.GroupRef>? AddToGroups { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.GroupRef> AddToGroups { get; set; }
#endif
        /// <summary>The businessPhones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BusinessPhones { get; set; }
#nullable restore
#else
        public List<string> BusinessPhones { get; set; }
#endif
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The companyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? CopyFrom { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue CopyFrom { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The defaultForTenant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultForTenant { get; set; }
#nullable restore
#else
        public string DefaultForTenant { get; set; }
#endif
        /// <summary>The department property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Department { get; set; }
#nullable restore
#else
        public string Department { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The givenName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>The groupMemberships property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupMemberships { get; set; }
#nullable restore
#else
        public string GroupMemberships { get; set; }
#endif
        /// <summary>The GUID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GUID { get; set; }
#nullable restore
#else
        public string GUID { get; set; }
#endif
        /// <summary>The jobTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobTitle { get; set; }
#nullable restore
#else
        public string JobTitle { get; set; }
#endif
        /// <summary>License SKU IDs to assign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Licenses { get; set; }
#nullable restore
#else
        public List<string> Licenses { get; set; }
#endif
        /// <summary>The mobilePhone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobilePhone { get; set; }
#nullable restore
#else
        public string MobilePhone { get; set; }
#endif
        /// <summary>The MustChangePass property</summary>
        public bool? MustChangePass { get; set; }
        /// <summary>The otherMails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? OtherMails { get; set; }
#nullable restore
#else
        public List<string> OtherMails { get; set; }
#endif
        /// <summary>The password property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The postalCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? PrimDomain { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue PrimDomain { get; set; }
#endif
        /// <summary>The removeLicenses property</summary>
        public bool? RemoveLicenses { get; set; }
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SetManager { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SetManager { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SetSponsor { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SetSponsor { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The streetAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreetAddress { get; set; }
#nullable restore
#else
        public string StreetAddress { get; set; }
#endif
        /// <summary>The surname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Surname { get; set; }
#nullable restore
#else
        public string Surname { get; set; }
#endif
        /// <summary>The templateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>The tenantFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? UsageLocation { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue UsageLocation { get; set; }
#endif
        /// <summary>The usernameFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsernameFormat { get; set; }
#nullable restore
#else
        public string UsernameFormat { get; set; }
#endif
        /// <summary>The usernameSpaceHandling property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsernameSpaceHandling { get; set; }
#nullable restore
#else
        public string UsernameSpaceHandling { get; set; }
#endif
        /// <summary>The usernameSpaceReplacement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsernameSpaceReplacement { get; set; }
#nullable restore
#else
        public string UsernameSpaceReplacement { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.AddUserDefaults.AddUserDefaultsPostRequestBody"/> and sets the default values.
        /// </summary>
        public AddUserDefaultsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.AddUserDefaults.AddUserDefaultsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.AddUserDefaults.AddUserDefaultsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.AddUserDefaults.AddUserDefaultsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addToGroups", n => { AddToGroups = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.GroupRef>(global::Bezalu.CIPP.Client.Models.GroupRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "addedAliases", n => { AddedAliases = n.GetStringValue(); } },
                { "businessPhones", n => { BusinessPhones = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "copyFrom", n => { CopyFrom = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "defaultForTenant", n => { DefaultForTenant = n.GetStringValue(); } },
                { "department", n => { Department = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "GUID", n => { GUID = n.GetStringValue(); } },
                { "givenName", n => { GivenName = n.GetStringValue(); } },
                { "groupMemberships", n => { GroupMemberships = n.GetStringValue(); } },
                { "jobTitle", n => { JobTitle = n.GetStringValue(); } },
                { "licenses", n => { Licenses = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mobilePhone", n => { MobilePhone = n.GetStringValue(); } },
                { "MustChangePass", n => { MustChangePass = n.GetBoolValue(); } },
                { "otherMails", n => { OtherMails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "primDomain", n => { PrimDomain = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "removeLicenses", n => { RemoveLicenses = n.GetBoolValue(); } },
                { "setManager", n => { SetManager = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "setSponsor", n => { SetSponsor = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "streetAddress", n => { StreetAddress = n.GetStringValue(); } },
                { "surname", n => { Surname = n.GetStringValue(); } },
                { "templateName", n => { TemplateName = n.GetStringValue(); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "usageLocation", n => { UsageLocation = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "usernameFormat", n => { UsernameFormat = n.GetStringValue(); } },
                { "usernameSpaceHandling", n => { UsernameSpaceHandling = n.GetStringValue(); } },
                { "usernameSpaceReplacement", n => { UsernameSpaceReplacement = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addedAliases", AddedAliases);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.GroupRef>("addToGroups", AddToGroups);
            writer.WriteCollectionOfPrimitiveValues<string>("businessPhones", BusinessPhones);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("copyFrom", CopyFrom);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("defaultForTenant", DefaultForTenant);
            writer.WriteStringValue("department", Department);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("givenName", GivenName);
            writer.WriteStringValue("groupMemberships", GroupMemberships);
            writer.WriteStringValue("GUID", GUID);
            writer.WriteStringValue("jobTitle", JobTitle);
            writer.WriteCollectionOfPrimitiveValues<string>("licenses", Licenses);
            writer.WriteStringValue("mobilePhone", MobilePhone);
            writer.WriteBoolValue("MustChangePass", MustChangePass);
            writer.WriteCollectionOfPrimitiveValues<string>("otherMails", OtherMails);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("primDomain", PrimDomain);
            writer.WriteBoolValue("removeLicenses", RemoveLicenses);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("setManager", SetManager);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("setSponsor", SetSponsor);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("streetAddress", StreetAddress);
            writer.WriteStringValue("surname", Surname);
            writer.WriteStringValue("templateName", TemplateName);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("usageLocation", UsageLocation);
            writer.WriteStringValue("usernameFormat", UsernameFormat);
            writer.WriteStringValue("usernameSpaceHandling", UsernameSpaceHandling);
            writer.WriteStringValue("usernameSpaceReplacement", UsernameSpaceReplacement);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
