// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bezalu.CIPP.Client.Api.ListAppStatus
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ListAppStatus
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListAppStatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListAppStatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ListAppStatus?tenantFilter={tenantFilter}{&AppFilter*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListAppStatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ListAppStatus?tenantFilter={tenantFilter}{&AppFilter*}", rawUrl)
        {
        }
        /// <summary>
        /// ListAppStatus
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Models.StandardResults"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults?> GetAsync(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder.ListAppStatusRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Bezalu.CIPP.Client.Models.StandardResults> GetAsync(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder.ListAppStatusRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Bezalu.CIPP.Client.Models.StandardResults>(requestInfo, global::Bezalu.CIPP.Client.Models.StandardResults.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListAppStatus
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder.ListAppStatusRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder.ListAppStatusRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListAppStatus
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListAppStatusRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? AppFilter { get; set; }
#nullable restore
#else
            public string AppFilter { get; set; }
#endif
            /// <summary>Target tenant domain or &apos;AllTenants&apos; for multi-tenant operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tenantFilter")]
            public string? TenantFilter { get; set; }
#nullable restore
#else
            [QueryParameter("tenantFilter")]
            public string TenantFilter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListAppStatusRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bezalu.CIPP.Client.Api.ListAppStatus.ListAppStatusRequestBuilder.ListAppStatusRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
