// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecGraphExplorerPreset
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecGraphExplorerPresetDeleteRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>action parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AsApp parameter</summary>
        public bool? AsApp { get; set; }
        /// <summary>endpoint parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>IsShared parameter</summary>
        public bool? IsShared { get; set; }
        /// <summary>name parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>NoPagination parameter</summary>
        public bool? NoPagination { get; set; }
        /// <summary>preset parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Preset { get; set; }
#nullable restore
#else
        public string Preset { get; set; }
#endif
        /// <summary>reportTemplate parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ReportTemplate { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ReportTemplate { get; set; }
#endif
        /// <summary>ReverseTenantLookup parameter</summary>
        public bool? ReverseTenantLookup { get; set; }
        /// <summary>ReverseTenantLookupProperty parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReverseTenantLookupProperty { get; set; }
#nullable restore
#else
        public string ReverseTenantLookupProperty { get; set; }
#endif
        /// <summary>version parameter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Version { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecGraphExplorerPreset.ExecGraphExplorerPresetDeleteRequestBody"/> and sets the default values.
        /// </summary>
        public ExecGraphExplorerPresetDeleteRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecGraphExplorerPreset.ExecGraphExplorerPresetDeleteRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecGraphExplorerPreset.ExecGraphExplorerPresetDeleteRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecGraphExplorerPreset.ExecGraphExplorerPresetDeleteRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "AsApp", n => { AsApp = n.GetBoolValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "IsShared", n => { IsShared = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "NoPagination", n => { NoPagination = n.GetBoolValue(); } },
                { "preset", n => { Preset = n.GetStringValue(); } },
                { "reportTemplate", n => { ReportTemplate = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "ReverseTenantLookup", n => { ReverseTenantLookup = n.GetBoolValue(); } },
                { "ReverseTenantLookupProperty", n => { ReverseTenantLookupProperty = n.GetStringValue(); } },
                { "version", n => { Version = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteBoolValue("AsApp", AsApp);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteBoolValue("IsShared", IsShared);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("NoPagination", NoPagination);
            writer.WriteStringValue("preset", Preset);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("reportTemplate", ReportTemplate);
            writer.WriteBoolValue("ReverseTenantLookup", ReverseTenantLookup);
            writer.WriteStringValue("ReverseTenantLookupProperty", ReverseTenantLookupProperty);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
