// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.CIPP.Client.Api.ListAppsRepository
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListAppsRepositoryPostRequestBody_AssignTo
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "On")]
        #pragma warning disable CS1591
        On,
        #pragma warning restore CS1591
        [EnumMember(Value = "allLicensedUsers")]
        #pragma warning disable CS1591
        AllLicensedUsers,
        #pragma warning restore CS1591
        [EnumMember(Value = "AllDevices")]
        #pragma warning disable CS1591
        AllDevices,
        #pragma warning restore CS1591
        [EnumMember(Value = "AllDevicesAndUsers")]
        #pragma warning disable CS1591
        AllDevicesAndUsers,
        #pragma warning restore CS1591
        [EnumMember(Value = "customGroup")]
        #pragma warning disable CS1591
        CustomGroup,
        #pragma warning restore CS1591
    }
}
