// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ListAppsRepository
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListAppsRepositoryPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AcceptLicense property</summary>
        public bool? AcceptLicense { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The applicationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationName { get; set; }
#nullable restore
#else
        public string ApplicationName { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? AppType { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue AppType { get; set; }
#endif
        /// <summary>The arch property</summary>
        public bool? Arch { get; set; }
        /// <summary>The AssignTo property</summary>
        public global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_AssignTo? AssignTo { get; set; }
        /// <summary>The customArguments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomArguments { get; set; }
#nullable restore
#else
        public string CustomArguments { get; set; }
#endif
        /// <summary>The customGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomGroup { get; set; }
#nullable restore
#else
        public string CustomGroup { get; set; }
#endif
        /// <summary>The customRepo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomRepo { get; set; }
#nullable restore
#else
        public string CustomRepo { get; set; }
#endif
        /// <summary>The customXml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomXml { get; set; }
#nullable restore
#else
        public string CustomXml { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The detectionFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionFile { get; set; }
#nullable restore
#else
        public string DetectionFile { get; set; }
#endif
        /// <summary>The detectionPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionPath { get; set; }
#nullable restore
#else
        public string DetectionPath { get; set; }
#endif
        /// <summary>The detectionScript property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetectionScript { get; set; }
#nullable restore
#else
        public string DetectionScript { get; set; }
#endif
        /// <summary>The DisableRestart property</summary>
        public bool? DisableRestart { get; set; }
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The enforceSignatureCheck property</summary>
        public bool? EnforceSignatureCheck { get; set; }
        /// <summary>The excludedApps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Bezalu.CIPP.Client.Models.LabelValue>? ExcludedApps { get; set; }
#nullable restore
#else
        public List<global::Bezalu.CIPP.Client.Models.LabelValue> ExcludedApps { get; set; }
#endif
        /// <summary>The InstallAsSystem property</summary>
        public bool? InstallAsSystem { get; set; }
        /// <summary>The InstallationIntent property</summary>
        public bool? InstallationIntent { get; set; }
        /// <summary>The installScript property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallScript { get; set; }
#nullable restore
#else
        public string InstallScript { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Languages { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Languages { get; set; }
#endif
        /// <summary>The packagename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Packagename { get; set; }
#nullable restore
#else
        public string Packagename { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? PackageSearch { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue PackageSearch { get; set; }
#endif
        /// <summary>The params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_params? Params { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_params Params { get; set; }
#endif
        /// <summary>The publisher property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Publisher { get; set; }
#nullable restore
#else
        public string Publisher { get; set; }
#endif
        /// <summary>The RemoveVersions property</summary>
        public bool? RemoveVersions { get; set; }
        /// <summary>Body parameter from PS1: Repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repository { get; set; }
#nullable restore
#else
        public string Repository { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Rmmname { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Rmmname { get; set; }
#endif
        /// <summary>The runAs32Bit property</summary>
        public bool? RunAs32Bit { get; set; }
        /// <summary>(auto) API uses &apos;Search&apos;, frontend sends &apos;searchQuery&apos; — likely the same field (similarity=0.71). Verify and correct type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Search { get; set; }
#nullable restore
#else
        public string Search { get; set; }
#endif
        /// <summary>The SharedComputerActivation property</summary>
        public bool? SharedComputerActivation { get; set; }
        /// <summary>The templateDescription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateDescription { get; set; }
#nullable restore
#else
        public string TemplateDescription { get; set; }
#endif
        /// <summary>The templateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>The uninstallScript property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UninstallScript { get; set; }
#nullable restore
#else
        public string UninstallScript { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? UpdateChannel { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue UpdateChannel { get; set; }
#endif
        /// <summary>The useCustomXml property</summary>
        public bool? UseCustomXml { get; set; }
        /// <summary>The useDetectionScript property</summary>
        public bool? UseDetectionScript { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody"/> and sets the default values.
        /// </summary>
        public ListAppsRepositoryPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AcceptLicense", n => { AcceptLicense = n.GetBoolValue(); } },
                { "appType", n => { AppType = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "applicationName", n => { ApplicationName = n.GetStringValue(); } },
                { "arch", n => { Arch = n.GetBoolValue(); } },
                { "AssignTo", n => { AssignTo = n.GetEnumValue<global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_AssignTo>(); } },
                { "customArguments", n => { CustomArguments = n.GetStringValue(); } },
                { "customGroup", n => { CustomGroup = n.GetStringValue(); } },
                { "customRepo", n => { CustomRepo = n.GetStringValue(); } },
                { "customXml", n => { CustomXml = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "detectionFile", n => { DetectionFile = n.GetStringValue(); } },
                { "detectionPath", n => { DetectionPath = n.GetStringValue(); } },
                { "detectionScript", n => { DetectionScript = n.GetStringValue(); } },
                { "DisableRestart", n => { DisableRestart = n.GetBoolValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "enforceSignatureCheck", n => { EnforceSignatureCheck = n.GetBoolValue(); } },
                { "excludedApps", n => { ExcludedApps = n.GetCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "InstallAsSystem", n => { InstallAsSystem = n.GetBoolValue(); } },
                { "installScript", n => { InstallScript = n.GetStringValue(); } },
                { "InstallationIntent", n => { InstallationIntent = n.GetBoolValue(); } },
                { "languages", n => { Languages = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "packageSearch", n => { PackageSearch = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "packagename", n => { Packagename = n.GetStringValue(); } },
                { "params", n => { Params = n.GetObjectValue<global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_params>(global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_params.CreateFromDiscriminatorValue); } },
                { "publisher", n => { Publisher = n.GetStringValue(); } },
                { "RemoveVersions", n => { RemoveVersions = n.GetBoolValue(); } },
                { "Repository", n => { Repository = n.GetStringValue(); } },
                { "rmmname", n => { Rmmname = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "runAs32Bit", n => { RunAs32Bit = n.GetBoolValue(); } },
                { "Search", n => { Search = n.GetStringValue(); } },
                { "SharedComputerActivation", n => { SharedComputerActivation = n.GetBoolValue(); } },
                { "templateDescription", n => { TemplateDescription = n.GetStringValue(); } },
                { "templateName", n => { TemplateName = n.GetStringValue(); } },
                { "uninstallScript", n => { UninstallScript = n.GetStringValue(); } },
                { "updateChannel", n => { UpdateChannel = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "useCustomXml", n => { UseCustomXml = n.GetBoolValue(); } },
                { "useDetectionScript", n => { UseDetectionScript = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AcceptLicense", AcceptLicense);
            writer.WriteStringValue("applicationName", ApplicationName);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("appType", AppType);
            writer.WriteBoolValue("arch", Arch);
            writer.WriteEnumValue<global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_AssignTo>("AssignTo", AssignTo);
            writer.WriteStringValue("customArguments", CustomArguments);
            writer.WriteStringValue("customGroup", CustomGroup);
            writer.WriteStringValue("customRepo", CustomRepo);
            writer.WriteStringValue("customXml", CustomXml);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("detectionFile", DetectionFile);
            writer.WriteStringValue("detectionPath", DetectionPath);
            writer.WriteStringValue("detectionScript", DetectionScript);
            writer.WriteBoolValue("DisableRestart", DisableRestart);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("enforceSignatureCheck", EnforceSignatureCheck);
            writer.WriteCollectionOfObjectValues<global::Bezalu.CIPP.Client.Models.LabelValue>("excludedApps", ExcludedApps);
            writer.WriteBoolValue("InstallAsSystem", InstallAsSystem);
            writer.WriteBoolValue("InstallationIntent", InstallationIntent);
            writer.WriteStringValue("installScript", InstallScript);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("languages", Languages);
            writer.WriteStringValue("packagename", Packagename);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("packageSearch", PackageSearch);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Api.ListAppsRepository.ListAppsRepositoryPostRequestBody_params>("params", Params);
            writer.WriteStringValue("publisher", Publisher);
            writer.WriteBoolValue("RemoveVersions", RemoveVersions);
            writer.WriteStringValue("Repository", Repository);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("rmmname", Rmmname);
            writer.WriteBoolValue("runAs32Bit", RunAs32Bit);
            writer.WriteStringValue("Search", Search);
            writer.WriteBoolValue("SharedComputerActivation", SharedComputerActivation);
            writer.WriteStringValue("templateDescription", TemplateDescription);
            writer.WriteStringValue("templateName", TemplateName);
            writer.WriteStringValue("uninstallScript", UninstallScript);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("updateChannel", UpdateChannel);
            writer.WriteBoolValue("useCustomXml", UseCustomXml);
            writer.WriteBoolValue("useDetectionScript", UseDetectionScript);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
