// <auto-generated/>
#pragma warning disable CS0618
using Bezalu.CIPP.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecCACheck
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecCACheckPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? AuthenticationFlow { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue AuthenticationFlow { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? ClientAppType { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue ClientAppType { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? Country { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue Country { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? DevicePlatform { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue DevicePlatform { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? IncludeApplications { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue IncludeApplications { get; set; }
#endif
        /// <summary>The IpAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpAddress { get; set; }
#nullable restore
#else
        public string IpAddress { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? SignInRiskLevel { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue SignInRiskLevel { get; set; }
#endif
        /// <summary>The tenantFilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenantFilter { get; set; }
#nullable restore
#else
        public string TenantFilter { get; set; }
#endif
        /// <summary>The userID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserID { get; set; }
#nullable restore
#else
        public string UserID { get; set; }
#endif
        /// <summary>Autocomplete/select field. Most dropdowns in CIPP use this shape. Backend typically unwraps via: $x.value ?? $x</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Bezalu.CIPP.Client.Models.LabelValue? UserRiskLevel { get; set; }
#nullable restore
#else
        public global::Bezalu.CIPP.Client.Models.LabelValue UserRiskLevel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecCACheck.ExecCACheckPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExecCACheckPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecCACheck.ExecCACheckPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecCACheck.ExecCACheckPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecCACheck.ExecCACheckPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authenticationFlow", n => { AuthenticationFlow = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "ClientAppType", n => { ClientAppType = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "Country", n => { Country = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "DevicePlatform", n => { DevicePlatform = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "IncludeApplications", n => { IncludeApplications = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "IpAddress", n => { IpAddress = n.GetStringValue(); } },
                { "SignInRiskLevel", n => { SignInRiskLevel = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
                { "tenantFilter", n => { TenantFilter = n.GetStringValue(); } },
                { "userID", n => { UserID = n.GetStringValue(); } },
                { "UserRiskLevel", n => { UserRiskLevel = n.GetObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>(global::Bezalu.CIPP.Client.Models.LabelValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("authenticationFlow", AuthenticationFlow);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("ClientAppType", ClientAppType);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("Country", Country);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("DevicePlatform", DevicePlatform);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("IncludeApplications", IncludeApplications);
            writer.WriteStringValue("IpAddress", IpAddress);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("SignInRiskLevel", SignInRiskLevel);
            writer.WriteStringValue("tenantFilter", TenantFilter);
            writer.WriteStringValue("userID", UserID);
            writer.WriteObjectValue<global::Bezalu.CIPP.Client.Models.LabelValue>("UserRiskLevel", UserRiskLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
