// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bezalu.CIPP.Client.Api.AddGroupTemplate
{
    /// <summary>(auto) from CippAddGroupTemplateForm.jsx</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddGroupTemplatePostRequestBody_groupType
    {
        [EnumMember(Value = "azurerole")]
        #pragma warning disable CS1591
        Azurerole,
        #pragma warning restore CS1591
        [EnumMember(Value = "generic")]
        #pragma warning disable CS1591
        Generic,
        #pragma warning restore CS1591
        [EnumMember(Value = "m365")]
        #pragma warning disable CS1591
        M365,
        #pragma warning restore CS1591
        [EnumMember(Value = "dynamic")]
        #pragma warning disable CS1591
        Dynamic,
        #pragma warning restore CS1591
        [EnumMember(Value = "dynamicDistribution")]
        #pragma warning disable CS1591
        DynamicDistribution,
        #pragma warning restore CS1591
        [EnumMember(Value = "distribution")]
        #pragma warning disable CS1591
        Distribution,
        #pragma warning restore CS1591
        [EnumMember(Value = "security")]
        #pragma warning disable CS1591
        Security,
        #pragma warning restore CS1591
    }
}
