// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bezalu.CIPP.Client.Api.ExecEditMailboxPermissions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExecEditMailboxPermissionsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The AddFullAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddFullAccess { get; set; }
#nullable restore
#else
        public string AddFullAccess { get; set; }
#endif
        /// <summary>The AddFullAccessNoAutoMap property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddFullAccessNoAutoMap { get; set; }
#nullable restore
#else
        public string AddFullAccessNoAutoMap { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AddSendAs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddSendAs { get; set; }
#nullable restore
#else
        public string AddSendAs { get; set; }
#endif
        /// <summary>The AddSendOnBehalf property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddSendOnBehalf { get; set; }
#nullable restore
#else
        public string AddSendOnBehalf { get; set; }
#endif
        /// <summary>The RemoveFullAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveFullAccess { get; set; }
#nullable restore
#else
        public string RemoveFullAccess { get; set; }
#endif
        /// <summary>The RemoveSendAs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveSendAs { get; set; }
#nullable restore
#else
        public string RemoveSendAs { get; set; }
#endif
        /// <summary>The RemoveSendOnBehalf property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveSendOnBehalf { get; set; }
#nullable restore
#else
        public string RemoveSendOnBehalf { get; set; }
#endif
        /// <summary>The tenantfilter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tenantfilter { get; set; }
#nullable restore
#else
        public string Tenantfilter { get; set; }
#endif
        /// <summary>The userID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserID { get; set; }
#nullable restore
#else
        public string UserID { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Bezalu.CIPP.Client.Api.ExecEditMailboxPermissions.ExecEditMailboxPermissionsPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExecEditMailboxPermissionsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bezalu.CIPP.Client.Api.ExecEditMailboxPermissions.ExecEditMailboxPermissionsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bezalu.CIPP.Client.Api.ExecEditMailboxPermissions.ExecEditMailboxPermissionsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Bezalu.CIPP.Client.Api.ExecEditMailboxPermissions.ExecEditMailboxPermissionsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AddFullAccess", n => { AddFullAccess = n.GetStringValue(); } },
                { "AddFullAccessNoAutoMap", n => { AddFullAccessNoAutoMap = n.GetStringValue(); } },
                { "AddSendAs", n => { AddSendAs = n.GetStringValue(); } },
                { "AddSendOnBehalf", n => { AddSendOnBehalf = n.GetStringValue(); } },
                { "RemoveFullAccess", n => { RemoveFullAccess = n.GetStringValue(); } },
                { "RemoveSendAs", n => { RemoveSendAs = n.GetStringValue(); } },
                { "RemoveSendOnBehalf", n => { RemoveSendOnBehalf = n.GetStringValue(); } },
                { "tenantfilter", n => { Tenantfilter = n.GetStringValue(); } },
                { "userID", n => { UserID = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AddFullAccess", AddFullAccess);
            writer.WriteStringValue("AddFullAccessNoAutoMap", AddFullAccessNoAutoMap);
            writer.WriteStringValue("AddSendAs", AddSendAs);
            writer.WriteStringValue("AddSendOnBehalf", AddSendOnBehalf);
            writer.WriteStringValue("RemoveFullAccess", RemoveFullAccess);
            writer.WriteStringValue("RemoveSendAs", RemoveSendAs);
            writer.WriteStringValue("RemoveSendOnBehalf", RemoveSendOnBehalf);
            writer.WriteStringValue("tenantfilter", Tenantfilter);
            writer.WriteStringValue("userID", UserID);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
